module DfE
  module ReferenceData
    module Demo
      HELLO_WORLD = DfE::ReferenceData::HardcodedReferenceList.new(
        {
          'en' => { text: 'Hello World' },
          'fr' => { text: 'Bounjour monde' },
          'jbo' => { text: 'coi rodo' },
        },
      )

      FICTIONAL_GREETINGS = DfE::ReferenceData::HardcodedReferenceList.new(
        {
          'dalek' => { text: 'OBEY! OBEY OR BE EXTERMINATED!' },
        },
      )

      ELEMENTS = DfE::ReferenceData::HardcodedReferenceList.new(
        {
          'H' => { atomic_number: 1, name: 'Hydrogen', atomic_mass: 1.007, number_of_neutrons: 0,
                   number_of_protons: 1, number_of_electrons: 1, period: 1, group: 1, phase: 'gas',
                   radioactive: false, natural: true, metal: false, nonmetal: true, metalloid: false,
                   type: 'Nonmetal', atomic_radius: 0.79, electronegativity: 2.2,
                   first_ionization: 13.5984, density: 8.99E-05, melting_point: 14.175, boiling_point: 20.28,
                   number_of_isotopes: 3, discoverer: 'Cavendish', year: 1766,
                   specific_heat: 14.304, number_of_shells: 1, valence: 1 },
          'He' => { atomic_number: 2, name: 'Helium', atomic_mass: 4.002, number_of_neutrons: 2,
                    number_of_protons: 2, number_of_electrons: 2, period: 1, group: 18, phase: 'gas',
                    radioactive: false, natural: true, metal: false, nonmetal: true, metalloid: false,
                    type: 'Noble Gas', atomic_radius: 0.49, electronegativity: nil,
                    first_ionization: 24.5874, density: 1.79E-04, melting_point: nil, boiling_point: 4.22,
                    number_of_isotopes: 5, discoverer: 'Janssen', year: 1868,
                    specific_heat: 5.193, number_of_shells: 1, valence: nil },
          'Li' => { atomic_number: 3, name: 'Lithium', atomic_mass: 6.941, number_of_neutrons: 4,
                    number_of_protons: 3, number_of_electrons: 3, period: 2, group: 1, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Alkali Metal', atomic_radius: 2.1, electronegativity: 0.98,
                    first_ionization: 5.3917, density: 5.34E-01, melting_point: 453.85, boiling_point: 1615,
                    number_of_isotopes: 5, discoverer: 'Arfvedson', year: 1817,
                    specific_heat: 3.582, number_of_shells: 2, valence: 1 },
          'Be' => { atomic_number: 4, name: 'Beryllium', atomic_mass: 9.012, number_of_neutrons: 5,
                    number_of_protons: 4, number_of_electrons: 4, period: 2, group: 2, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Alkaline Earth Metal', atomic_radius: 1.4, electronegativity: 1.57,
                    first_ionization: 9.3227, density: 1.85E+00, melting_point: 1560.15, boiling_point: 2742,
                    number_of_isotopes: 6, discoverer: 'Vaulquelin', year: 1798,
                    specific_heat: 1.825, number_of_shells: 2, valence: 2 },
          'B' => { atomic_number: 5, name: 'Boron', atomic_mass: 10.811, number_of_neutrons: 6,
                   number_of_protons: 5, number_of_electrons: 5, period: 2, group: 13, phase: 'solid',
                   radioactive: false, natural: true, metal: false, nonmetal: false, metalloid: true,
                   type: 'Metalloid', atomic_radius: 1.2, electronegativity: 2.04,
                   first_ionization: 8.298, density: 2.34E+00, melting_point: 2573.15, boiling_point: 4200,
                   number_of_isotopes: 6, discoverer: 'Gay-Lussac', year: 1808,
                   specific_heat: 1.026, number_of_shells: 2, valence: 3 },
          'C' => { atomic_number: 6, name: 'Carbon', atomic_mass: 12.011, number_of_neutrons: 6,
                   number_of_protons: 6, number_of_electrons: 6, period: 2, group: 14, phase: 'solid',
                   radioactive: false, natural: true, metal: false, nonmetal: true, metalloid: false,
                   type: 'Nonmetal', atomic_radius: 0.91, electronegativity: 2.55,
                   first_ionization: 11.2603, density: 2.27E+00, melting_point: 3948.15, boiling_point: 4300,
                   number_of_isotopes: 7, discoverer: 'Prehistoric', year: nil,
                   specific_heat: 0.709, number_of_shells: 2, valence: 4 },
          'N' => { atomic_number: 7, name: 'Nitrogen', atomic_mass: 14.007, number_of_neutrons: 7,
                   number_of_protons: 7, number_of_electrons: 7, period: 2, group: 15, phase: 'gas',
                   radioactive: false, natural: true, metal: false, nonmetal: true, metalloid: false,
                   type: 'Nonmetal', atomic_radius: 0.75, electronegativity: 3.04,
                   first_ionization: 14.5341, density: 1.25E-03, melting_point: 63.29, boiling_point: 77.36,
                   number_of_isotopes: 8, discoverer: 'Rutherford', year: 1772,
                   specific_heat: 1.04, number_of_shells: 2, valence: 5 },
          'O' => { atomic_number: 8, name: 'Oxygen', atomic_mass: 15.999, number_of_neutrons: 8,
                   number_of_protons: 8, number_of_electrons: 8, period: 2, group: 16, phase: 'gas',
                   radioactive: false, natural: true, metal: false, nonmetal: true, metalloid: false,
                   type: 'Nonmetal', atomic_radius: 0.65, electronegativity: 3.44,
                   first_ionization: 13.6181, density: 1.43E-03, melting_point: 50.5, boiling_point: 90.2,
                   number_of_isotopes: 8, discoverer: 'Priestley/Scheele', year: 1774,
                   specific_heat: 0.918, number_of_shells: 2, valence: 6 },
          'F' => { atomic_number: 9, name: 'Fluorine', atomic_mass: 18.998, number_of_neutrons: 10,
                   number_of_protons: 9, number_of_electrons: 9, period: 2, group: 17, phase: 'gas',
                   radioactive: false, natural: true, metal: false, nonmetal: true, metalloid: false,
                   type: 'Halogen', atomic_radius: 0.57, electronegativity: 3.98,
                   first_ionization: 17.4228, density: 1.70E-03, melting_point: 53.63, boiling_point: 85.03,
                   number_of_isotopes: 6, discoverer: 'Moissan', year: 1886,
                   specific_heat: 0.824, number_of_shells: 2, valence: 7 },
          'Ne' => { atomic_number: 10, name: 'Neon', atomic_mass: 20.18, number_of_neutrons: 10,
                    number_of_protons: 10, number_of_electrons: 10, period: 2, group: 18, phase: 'gas',
                    radioactive: false, natural: true, metal: false, nonmetal: true, metalloid: false,
                    type: 'Noble Gas', atomic_radius: 0.51, electronegativity: nil,
                    first_ionization: 21.5645, density: 9.00E-04, melting_point: 24.703, boiling_point: 27.07,
                    number_of_isotopes: 8, discoverer: 'Ramsay and Travers', year: 1898,
                    specific_heat: 1.03, number_of_shells: 2, valence: 8 },
          'Na' => { atomic_number: 11, name: 'Sodium', atomic_mass: 22.99, number_of_neutrons: 12,
                    number_of_protons: 11, number_of_electrons: 11, period: 3, group: 1, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Alkali Metal', atomic_radius: 2.2, electronegativity: 0.93,
                    first_ionization: 5.1391, density: 9.71E-01, melting_point: 371.15, boiling_point: 1156,
                    number_of_isotopes: 7, discoverer: 'Davy', year: 1807,
                    specific_heat: 1.228, number_of_shells: 3, valence: 1 },
          'Mg' => { atomic_number: 12, name: 'Magnesium', atomic_mass: 24.305, number_of_neutrons: 12,
                    number_of_protons: 12, number_of_electrons: 12, period: 3, group: 2, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Alkaline Earth Metal', atomic_radius: 1.7, electronegativity: 1.31,
                    first_ionization: 7.6462, density: 1.74E+00, melting_point: 923.15, boiling_point: 1363,
                    number_of_isotopes: 8, discoverer: 'Black', year: 1755,
                    specific_heat: 1.023, number_of_shells: 3, valence: 2 },
          'Al' => { atomic_number: 13, name: 'Aluminum', atomic_mass: 26.982, number_of_neutrons: 14,
                    number_of_protons: 13, number_of_electrons: 13, period: 3, group: 13, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Metal', atomic_radius: 1.8, electronegativity: 1.61,
                    first_ionization: 5.9858, density: 2.70E+00, melting_point: 933.4, boiling_point: 2792,
                    number_of_isotopes: 8, discoverer: 'Wshler', year: 1827,
                    specific_heat: 0.897, number_of_shells: 3, valence: 3 },
          'Si' => { atomic_number: 14, name: 'Silicon', atomic_mass: 28.086, number_of_neutrons: 14,
                    number_of_protons: 14, number_of_electrons: 14, period: 3, group: 14, phase: 'solid',
                    radioactive: false, natural: true, metal: false, nonmetal: false, metalloid: true,
                    type: 'Metalloid', atomic_radius: 1.5, electronegativity: 1.9,
                    first_ionization: 8.1517, density: 2.33E+00, melting_point: 1683.15, boiling_point: 3538,
                    number_of_isotopes: 8, discoverer: 'Berzelius', year: 1824,
                    specific_heat: 0.705, number_of_shells: 3, valence: 4 },
          'P' => { atomic_number: 15, name: 'Phosphorus', atomic_mass: 30.974, number_of_neutrons: 16,
                   number_of_protons: 15, number_of_electrons: 15, period: 3, group: 15, phase: 'solid',
                   radioactive: false, natural: true, metal: false, nonmetal: true, metalloid: false,
                   type: 'Nonmetal', atomic_radius: 1.2, electronegativity: 2.19,
                   first_ionization: 10.4867, density: 1.82E+00, melting_point: 317.25, boiling_point: 553,
                   number_of_isotopes: 7, discoverer: 'BranBrand', year: 1669,
                   specific_heat: 0.769, number_of_shells: 3, valence: 5 },
          'S' => { atomic_number: 16, name: 'Sulfur', atomic_mass: 32.065, number_of_neutrons: 16,
                   number_of_protons: 16, number_of_electrons: 16, period: 3, group: 16, phase: 'solid',
                   radioactive: false, natural: true, metal: false, nonmetal: true, metalloid: false,
                   type: 'Nonmetal', atomic_radius: 1.1, electronegativity: 2.58,
                   first_ionization: 10.36, density: 2.07E+00, melting_point: 388.51, boiling_point: 717.8,
                   number_of_isotopes: 10, discoverer: 'Prehistoric', year: nil,
                   specific_heat: 0.71, number_of_shells: 3, valence: 6 },
          'Cl' => { atomic_number: 17, name: 'Chlorine', atomic_mass: 35.453, number_of_neutrons: 18,
                    number_of_protons: 17, number_of_electrons: 17, period: 3, group: 17, phase: 'gas',
                    radioactive: false, natural: true, metal: false, nonmetal: true, metalloid: false,
                    type: 'Halogen', atomic_radius: 0.97, electronegativity: 3.16,
                    first_ionization: 12.9676, density: 3.21E-03, melting_point: 172.31, boiling_point: 239.11,
                    number_of_isotopes: 11, discoverer: 'Scheele', year: 1774,
                    specific_heat: 0.479, number_of_shells: 3, valence: 7 },
          'Ar' => { atomic_number: 18, name: 'Argon', atomic_mass: 39.948, number_of_neutrons: 22,
                    number_of_protons: 18, number_of_electrons: 18, period: 3, group: 18, phase: 'gas',
                    radioactive: false, natural: true, metal: false, nonmetal: true, metalloid: false,
                    type: 'Noble Gas', atomic_radius: 0.88, electronegativity: nil,
                    first_ionization: 15.7596, density: 1.78E-03, melting_point: 83.96, boiling_point: 87.3,
                    number_of_isotopes: 8, discoverer: 'Rayleigh and Ramsay', year: 1894,
                    specific_heat: 0.52, number_of_shells: 3, valence: 8 },
          'K' => { atomic_number: 19, name: 'Potassium', atomic_mass: 39.098, number_of_neutrons: 20,
                   number_of_protons: 19, number_of_electrons: 19, period: 4, group: 1, phase: 'solid',
                   radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                   type: 'Alkali Metal', atomic_radius: 2.8, electronegativity: 0.82,
                   first_ionization: 4.3407, density: 8.62E-01, melting_point: 336.5, boiling_point: 1032,
                   number_of_isotopes: 10, discoverer: 'Davy', year: 1807,
                   specific_heat: 0.757, number_of_shells: 4, valence: 1 },
          'Ca' => { atomic_number: 20, name: 'Calcium', atomic_mass: 40.078, number_of_neutrons: 20,
                    number_of_protons: 20, number_of_electrons: 20, period: 4, group: 2, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Alkaline Earth Metal', atomic_radius: 2.2, electronegativity: 1,
                    first_ionization: 6.1132, density: 1.54E+00, melting_point: 1112.15, boiling_point: 1757,
                    number_of_isotopes: 14, discoverer: 'Davy', year: 1808,
                    specific_heat: 0.647, number_of_shells: 4, valence: 2 },
          'Sc' => { atomic_number: 21, name: 'Scandium', atomic_mass: 44.956, number_of_neutrons: 24,
                    number_of_protons: 21, number_of_electrons: 21, period: 4, group: 3, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Transition Metal', atomic_radius: 2.1, electronegativity: 1.36,
                    first_ionization: 6.5615, density: 2.99E+00, melting_point: 1812.15, boiling_point: 3109,
                    number_of_isotopes: 15, discoverer: 'Nilson', year: 1878,
                    specific_heat: 0.568, number_of_shells: 4, valence: nil },
          'Ti' => { atomic_number: 22, name: 'Titanium', atomic_mass: 47.867, number_of_neutrons: 26,
                    number_of_protons: 22, number_of_electrons: 22, period: 4, group: 4, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Transition Metal', atomic_radius: 2, electronegativity: 1.54,
                    first_ionization: 6.8281, density: 4.54E+00, melting_point: 1933.15, boiling_point: 3560,
                    number_of_isotopes: 9, discoverer: 'Gregor', year: 1791,
                    specific_heat: 0.523, number_of_shells: 4, valence: nil },
          'V' => { atomic_number: 23, name: 'Vanadium', atomic_mass: 50.942, number_of_neutrons: 28,
                   number_of_protons: 23, number_of_electrons: 23, period: 4, group: 5, phase: 'solid',
                   radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                   type: 'Transition Metal', atomic_radius: 1.9, electronegativity: 1.63,
                   first_ionization: 6.7462, density: 6.11E+00, melting_point: 2175.15, boiling_point: 3680,
                   number_of_isotopes: 9, discoverer: '   del Rio', year: 1801,
                   specific_heat: 0.489, number_of_shells: 4, valence: nil },
          'Cr' => { atomic_number: 24, name: 'Chromium', atomic_mass: 51.996, number_of_neutrons: 28,
                    number_of_protons: 24, number_of_electrons: 24, period: 4, group: 6, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Transition Metal', atomic_radius: 1.9, electronegativity: 1.66,
                    first_ionization: 6.7665, density: 7.15E+00, melting_point: 2130.15, boiling_point: 2944,
                    number_of_isotopes: 9, discoverer: 'Vauquelin', year: 1797,
                    specific_heat: 0.449, number_of_shells: 4, valence: nil },
          'Mn' => { atomic_number: 25, name: 'Manganese', atomic_mass: 54.938, number_of_neutrons: 30,
                    number_of_protons: 25, number_of_electrons: 25, period: 4, group: 7, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Transition Metal', atomic_radius: 1.8, electronegativity: 1.55,
                    first_ionization: 7.434, density: 7.44E+00, melting_point: 1519.15, boiling_point: 2334,
                    number_of_isotopes: 11, discoverer: 'Gahn+Scheele', year: 1774,
                    specific_heat: 0.479, number_of_shells: 4, valence: nil },
          'Fe' => { atomic_number: 26, name: 'Iron', atomic_mass: 55.845, number_of_neutrons: 30,
                    number_of_protons: 26, number_of_electrons: 26, period: 4, group: 8, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Transition Metal', atomic_radius: 1.7, electronegativity: 1.83,
                    first_ionization: 7.9024, density: 7.87E+00, melting_point: 1808.15, boiling_point: 3134,
                    number_of_isotopes: 10, discoverer: 'Prehistoric', year: nil,
                    specific_heat: 0.449, number_of_shells: 4, valence: nil },
          'Co' => { atomic_number: 27, name: 'Cobalt', atomic_mass: 58.933, number_of_neutrons: 32,
                    number_of_protons: 27, number_of_electrons: 27, period: 4, group: 9, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Transition Metal', atomic_radius: 1.7, electronegativity: 1.88,
                    first_ionization: 7.881, density: 8.86E+00, melting_point: 1768.15, boiling_point: 3200,
                    number_of_isotopes: 14, discoverer: 'Brandt', year: 1735,
                    specific_heat: 0.421, number_of_shells: 4, valence: nil },
          'Ni' => { atomic_number: 28, name: 'Nickel', atomic_mass: 58.693, number_of_neutrons: 31,
                    number_of_protons: 28, number_of_electrons: 28, period: 4, group: 10, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Transition Metal', atomic_radius: 1.6, electronegativity: 1.91,
                    first_ionization: 7.6398, density: 8.91E+00, melting_point: 1726.15, boiling_point: 3186,
                    number_of_isotopes: 11, discoverer: 'Cronstedt', year: 1751,
                    specific_heat: 0.444, number_of_shells: 4, valence: nil },
          'Cu' => { atomic_number: 29, name: 'Copper', atomic_mass: 63.546, number_of_neutrons: 35,
                    number_of_protons: 29, number_of_electrons: 29, period: 4, group: 11, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Transition Metal', atomic_radius: 1.6, electronegativity: 1.9,
                    first_ionization: 7.7264, density: 8.96E+00, melting_point: 1357.75, boiling_point: 2835,
                    number_of_isotopes: 11, discoverer: 'Prehistoric', year: nil,
                    specific_heat: 0.385, number_of_shells: 4, valence: nil },
          'Zn' => { atomic_number: 30, name: 'Zinc', atomic_mass: 65.38, number_of_neutrons: 35,
                    number_of_protons: 30, number_of_electrons: 30, period: 4, group: 12, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Transition Metal', atomic_radius: 1.5, electronegativity: 1.65,
                    first_ionization: 9.3942, density: 7.13E+00, melting_point: 692.88, boiling_point: 1180,
                    number_of_isotopes: 15, discoverer: 'Prehistoric', year: nil,
                    specific_heat: 0.388, number_of_shells: 4, valence: nil },
          'Ga' => { atomic_number: 31, name: 'Gallium', atomic_mass: 69.723, number_of_neutrons: 39,
                    number_of_protons: 31, number_of_electrons: 31, period: 4, group: 13, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Metal', atomic_radius: 1.8, electronegativity: 1.81,
                    first_ionization: 5.9993, density: 5.91E+00, melting_point: 302.91, boiling_point: 2477,
                    number_of_isotopes: 14, discoverer: 'de Boisbaudran', year: 1875,
                    specific_heat: 0.371, number_of_shells: 4, valence: 3 },
          'Ge' => { atomic_number: 32, name: 'Germanium', atomic_mass: 72.64, number_of_neutrons: 41,
                    number_of_protons: 32, number_of_electrons: 32, period: 4, group: 14, phase: 'solid',
                    radioactive: false, natural: true, metal: false, nonmetal: false, metalloid: true,
                    type: 'Metalloid', atomic_radius: 1.5, electronegativity: 2.01,
                    first_ionization: 7.8994, density: 5.32E+00, melting_point: 1211.45, boiling_point: 3106,
                    number_of_isotopes: 17, discoverer: 'Winkler', year: 1886,
                    specific_heat: 0.32, number_of_shells: 4, valence: 4 },
          'As' => { atomic_number: 33, name: 'Arsenic', atomic_mass: 74.922, number_of_neutrons: 42,
                    number_of_protons: 33, number_of_electrons: 33, period: 4, group: 15, phase: 'solid',
                    radioactive: false, natural: true, metal: false, nonmetal: false, metalloid: true,
                    type: 'Metalloid', atomic_radius: 1.3, electronegativity: 2.18,
                    first_ionization: 9.7886, density: 5.78E+00, melting_point: 1090.15, boiling_point: 887,
                    number_of_isotopes: 14, discoverer: 'Albertus Magnus', year: 1250,
                    specific_heat: 0.329, number_of_shells: 4, valence: 5 },
          'Se' => { atomic_number: 34, name: 'Selenium', atomic_mass: 78.96, number_of_neutrons: 45,
                    number_of_protons: 34, number_of_electrons: 34, period: 4, group: 16, phase: 'solid',
                    radioactive: false, natural: true, metal: false, nonmetal: true, metalloid: false,
                    type: 'Nonmetal', atomic_radius: 1.2, electronegativity: 2.55,
                    first_ionization: 9.7524, density: 4.81E+00, melting_point: 494.15, boiling_point: 958,
                    number_of_isotopes: 20, discoverer: 'Berzelius', year: 1817,
                    specific_heat: 0.321, number_of_shells: 4, valence: 6 },
          'Br' => { atomic_number: 35, name: 'Bromine', atomic_mass: 79.904, number_of_neutrons: 45,
                    number_of_protons: 35, number_of_electrons: 35, period: 4, group: 17, phase: 'liq',
                    radioactive: false, natural: true, metal: false, nonmetal: true, metalloid: false,
                    type: 'Halogen', atomic_radius: 1.1, electronegativity: 2.96,
                    first_ionization: 11.8138, density: 3.12E+00, melting_point: 266.05, boiling_point: 332,
                    number_of_isotopes: 19, discoverer: 'Balard', year: 1826,
                    specific_heat: 0.474, number_of_shells: 4, valence: 7 },
          'Kr' => { atomic_number: 36, name: 'Krypton', atomic_mass: 83.798, number_of_neutrons: 48,
                    number_of_protons: 36, number_of_electrons: 36, period: 4, group: 18, phase: 'gas',
                    radioactive: false, natural: true, metal: false, nonmetal: true, metalloid: false,
                    type: 'Noble Gas', atomic_radius: 1, electronegativity: nil,
                    first_ionization: 13.9996, density: 3.73E-03, melting_point: 115.93, boiling_point: 119.93,
                    number_of_isotopes: 23, discoverer: 'Ramsay and Travers', year: 1898,
                    specific_heat: 0.248, number_of_shells: 4, valence: 8 },
          'Rb' => { atomic_number: 37, name: 'Rubidium', atomic_mass: 85.468, number_of_neutrons: 48,
                    number_of_protons: 37, number_of_electrons: 37, period: 5, group: 1, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Alkali Metal', atomic_radius: 3, electronegativity: 0.82,
                    first_ionization: 4.1771, density: 1.53E+00, melting_point: 312.79, boiling_point: 961,
                    number_of_isotopes: 20, discoverer: 'Bunsen and Kirchoff', year: 1861,
                    specific_heat: 0.363, number_of_shells: 5, valence: 1 },
          'Sr' => { atomic_number: 38, name: 'Strontium', atomic_mass: 87.62, number_of_neutrons: 50,
                    number_of_protons: 38, number_of_electrons: 38, period: 5, group: 2, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Alkaline Earth Metal', atomic_radius: 2.5, electronegativity: 0.95,
                    first_ionization: 5.6949, density: 2.64E+00, melting_point: 1042.15, boiling_point: 1655,
                    number_of_isotopes: 18, discoverer: 'Davy', year: 1808,
                    specific_heat: 0.301, number_of_shells: 5, valence: 2 },
          'Y' => { atomic_number: 39, name: 'Yttrium', atomic_mass: 88.906, number_of_neutrons: 50,
                   number_of_protons: 39, number_of_electrons: 39, period: 5, group: 3, phase: 'solid',
                   radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                   type: 'Transition Metal', atomic_radius: 2.3, electronegativity: 1.22,
                   first_ionization: 6.2173, density: 4.47E+00, melting_point: 1799.15, boiling_point: 3609,
                   number_of_isotopes: 21, discoverer: 'Gadolin', year: 1794,
                   specific_heat: 0.298, number_of_shells: 5, valence: nil },
          'Zr' => { atomic_number: 40, name: 'Zirconium', atomic_mass: 91.224, number_of_neutrons: 51,
                    number_of_protons: 40, number_of_electrons: 40, period: 5, group: 4, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Transition Metal', atomic_radius: 2.2, electronegativity: 1.33,
                    first_ionization: 6.6339, density: 6.51E+00, melting_point: 2125.15, boiling_point: 4682,
                    number_of_isotopes: 20, discoverer: 'Klaproth', year: 1789,
                    specific_heat: 0.278, number_of_shells: 5, valence: nil },
          'Nb' => { atomic_number: 41, name: 'Niobium', atomic_mass: 92.906, number_of_neutrons: 52,
                    number_of_protons: 41, number_of_electrons: 41, period: 5, group: 5, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Transition Metal', atomic_radius: 2.1, electronegativity: 1.6,
                    first_ionization: 6.7589, density: 8.57E+00, melting_point: 2741.15, boiling_point: 5017,
                    number_of_isotopes: 24, discoverer: 'Hatchett', year: 1801,
                    specific_heat: 0.265, number_of_shells: 5, valence: nil },
          'Mo' => { atomic_number: 42, name: 'Molybdenum', atomic_mass: 95.96, number_of_neutrons: 54,
                    number_of_protons: 42, number_of_electrons: 42, period: 5, group: 6, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Transition Metal', atomic_radius: 2, electronegativity: 2.16,
                    first_ionization: 7.0924, density: 1.02E+01, melting_point: 2890.15, boiling_point: 4912,
                    number_of_isotopes: 20, discoverer: 'Scheele', year: 1778,
                    specific_heat: 0.251, number_of_shells: 5, valence: nil },
          'Tc' => { atomic_number: 43, name: 'Technetium', atomic_mass: 98, number_of_neutrons: 55,
                    number_of_protons: 43, number_of_electrons: 43, period: 5, group: 7, phase: 'artificial',
                    radioactive: true, natural: false, metal: true, nonmetal: false, metalloid: false,
                    type: 'Transition Metal', atomic_radius: 2, electronegativity: 1.9,
                    first_ionization: 7.28, density: 1.15E+01, melting_point: 2473.15, boiling_point: 5150,
                    number_of_isotopes: 23, discoverer: 'Perrier and Segr\xef\xbf\xbd', year: 1937,
                    specific_heat: nil, number_of_shells: 5, valence: nil },
          'Ru' => { atomic_number: 44, name: 'Ruthenium', atomic_mass: 101.07, number_of_neutrons: 57,
                    number_of_protons: 44, number_of_electrons: 44, period: 5, group: 8, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Transition Metal', atomic_radius: 1.9, electronegativity: 2.2,
                    first_ionization: 7.3605, density: 1.24E+01, melting_point: 2523.15, boiling_point: 4423,
                    number_of_isotopes: 16, discoverer: 'Klaus', year: 1844,
                    specific_heat: 0.238, number_of_shells: 5, valence: nil },
          'Rh' => { atomic_number: 45, name: 'Rhodium', atomic_mass: 102.906, number_of_neutrons: 58,
                    number_of_protons: 45, number_of_electrons: 45, period: 5, group: 9, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Transition Metal', atomic_radius: 1.8, electronegativity: 2.28,
                    first_ionization: 7.4589, density: 1.24E+01, melting_point: 2239.15, boiling_point: 3968,
                    number_of_isotopes: 20, discoverer: 'Wollaston', year: 1803,
                    specific_heat: 0.243, number_of_shells: 5, valence: nil },
          'Pd' => { atomic_number: 46, name: 'Palladium', atomic_mass: 106.42, number_of_neutrons: 60,
                    number_of_protons: 46, number_of_electrons: 46, period: 5, group: 10, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Transition Metal', atomic_radius: 1.8, electronegativity: 2.2,
                    first_ionization: 8.3369, density: 1.20E+01, melting_point: 1825.15, boiling_point: 3236,
                    number_of_isotopes: 21, discoverer: 'Wollaston', year: 1803,
                    specific_heat: 0.244, number_of_shells: 5, valence: nil },
          'Ag' => { atomic_number: 47, name: 'Silver', atomic_mass: 107.868, number_of_neutrons: 61,
                    number_of_protons: 47, number_of_electrons: 47, period: 5, group: 11, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Transition Metal', atomic_radius: 1.8, electronegativity: 1.93,
                    first_ionization: 7.5762, density: 1.05E+01, melting_point: 1234.15, boiling_point: 2435,
                    number_of_isotopes: 27, discoverer: 'Prehistoric', year: nil,
                    specific_heat: 0.235, number_of_shells: 5, valence: nil },
          'Cd' => { atomic_number: 48, name: 'Cadmium', atomic_mass: 112.411, number_of_neutrons: 64,
                    number_of_protons: 48, number_of_electrons: 48, period: 5, group: 12, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Transition Metal', atomic_radius: 1.7, electronegativity: 1.69,
                    first_ionization: 8.9938, density: 8.69E+00, melting_point: 594.33, boiling_point: 1040,
                    number_of_isotopes: 22, discoverer: 'Stromeyer', year: 1817,
                    specific_heat: 0.232, number_of_shells: 5, valence: nil },
          'In' => { atomic_number: 49, name: 'Indium', atomic_mass: 114.818, number_of_neutrons: 66,
                    number_of_protons: 49, number_of_electrons: 49, period: 5, group: 13, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Metal', atomic_radius: 2, electronegativity: 1.78,
                    first_ionization: 5.7864, density: 7.31E+00, melting_point: 429.91, boiling_point: 2345,
                    number_of_isotopes: 34, discoverer: 'Reich and Richter', year: 1863,
                    specific_heat: 0.233, number_of_shells: 5, valence: 3 },
          'Sn' => { atomic_number: 50, name: 'Tin', atomic_mass: 118.71, number_of_neutrons: 69,
                    number_of_protons: 50, number_of_electrons: 50, period: 5, group: 14, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Metal', atomic_radius: 1.7, electronegativity: 1.96,
                    first_ionization: 7.3439, density: 7.29E+00, melting_point: 505.21, boiling_point: 2875,
                    number_of_isotopes: 28, discoverer: 'Prehistoric', year: nil,
                    specific_heat: 0.228, number_of_shells: 5, valence: 4 },
          'Sb' => { atomic_number: 51, name: 'Antimony', atomic_mass: 121.76, number_of_neutrons: 71,
                    number_of_protons: 51, number_of_electrons: 51, period: 5, group: 15, phase: 'solid',
                    radioactive: false, natural: true, metal: false, nonmetal: false, metalloid: true,
                    type: 'Metalloid', atomic_radius: 1.5, electronegativity: 2.05,
                    first_ionization: 8.6084, density: 6.69E+00, melting_point: 904.05, boiling_point: 1860,
                    number_of_isotopes: 29, discoverer: 'Early historic times', year: nil,
                    specific_heat: 0.207, number_of_shells: 5, valence: 5 },
          'Te' => { atomic_number: 52, name: 'Tellurium', atomic_mass: 127.6, number_of_neutrons: 76,
                    number_of_protons: 52, number_of_electrons: 52, period: 5, group: 16, phase: 'solid',
                    radioactive: false, natural: true, metal: false, nonmetal: false, metalloid: true,
                    type: 'Metalloid', atomic_radius: 1.4, electronegativity: 2.1,
                    first_ionization: 9.0096, density: 6.23E+00, melting_point: 722.8, boiling_point: 1261,
                    number_of_isotopes: 29, discoverer: 'von Reichenstein', year: 1782,
                    specific_heat: 0.202, number_of_shells: 5, valence: 6 },
          'I' => { atomic_number: 53, name: 'Iodine', atomic_mass: 126.904, number_of_neutrons: 74,
                   number_of_protons: 53, number_of_electrons: 53, period: 5, group: 17, phase: 'solid',
                   radioactive: false, natural: true, metal: false, nonmetal: true, metalloid: false,
                   type: 'Halogen', atomic_radius: 1.3, electronegativity: 2.66,
                   first_ionization: 10.4513, density: 4.93E+00, melting_point: 386.65, boiling_point: 457.4,
                   number_of_isotopes: 24, discoverer: 'Courtois', year: 1811,
                   specific_heat: 0.214, number_of_shells: 5, valence: 7 },
          'Xe' => { atomic_number: 54, name: 'Xenon', atomic_mass: 131.293, number_of_neutrons: 77,
                    number_of_protons: 54, number_of_electrons: 54, period: 5, group: 18, phase: 'gas',
                    radioactive: false, natural: true, metal: false, nonmetal: true, metalloid: false,
                    type: 'Noble Gas', atomic_radius: 1.2, electronegativity: nil,
                    first_ionization: 12.1298, density: 5.89E-03, melting_point: 161.45, boiling_point: 165.03,
                    number_of_isotopes: 31, discoverer: 'Ramsay and Travers', year: 1898,
                    specific_heat: 0.158, number_of_shells: 5, valence: 8 },
          'Cs' => { atomic_number: 55, name: 'Cesium', atomic_mass: 132.905, number_of_neutrons: 78,
                    number_of_protons: 55, number_of_electrons: 55, period: 6, group: 1, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Alkali Metal', atomic_radius: 3.3, electronegativity: 0.79,
                    first_ionization: 3.8939, density: 1.87E+00, melting_point: 301.7, boiling_point: 944,
                    number_of_isotopes: 22, discoverer: 'Bunsen and Kirchoff', year: 1860,
                    specific_heat: 0.242, number_of_shells: 6, valence: 1 },
          'Ba' => { atomic_number: 56, name: 'Barium', atomic_mass: 137.327, number_of_neutrons: 81,
                    number_of_protons: 56, number_of_electrons: 56, period: 6, group: 2, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Alkaline Earth Metal', atomic_radius: 2.8, electronegativity: 0.89,
                    first_ionization: 5.2117, density: 3.59E+00, melting_point: 1002.15, boiling_point: 2170,
                    number_of_isotopes: 25, discoverer: 'Davy', year: 1808,
                    specific_heat: 0.204, number_of_shells: 6, valence: 2 },
          'La' => { atomic_number: 57, name: 'Lanthanum', atomic_mass: 138.905, number_of_neutrons: 82,
                    number_of_protons: 57, number_of_electrons: 57, period: 6, group: 3, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Lanthanide', atomic_radius: 2.7, electronegativity: 1.1,
                    first_ionization: 5.5769, density: 6.15E+00, melting_point: 1193.15, boiling_point: 3737,
                    number_of_isotopes: 19, discoverer: 'Mosander', year: 1839,
                    specific_heat: 0.195, number_of_shells: 6, valence: nil },
          'Ce' => { atomic_number: 58, name: 'Cerium', atomic_mass: 140.116, number_of_neutrons: 82,
                    number_of_protons: 58, number_of_electrons: 58, period: 6, group: nil, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Lanthanide', atomic_radius: 2.7, electronegativity: 1.12,
                    first_ionization: 5.5387, density: 6.77E+00, melting_point: 1071.15, boiling_point: 3716,
                    number_of_isotopes: 19, discoverer: 'Berzelius', year: 1803,
                    specific_heat: 0.192, number_of_shells: 6, valence: nil },
          'Pr' => { atomic_number: 59, name: 'Praseodymium', atomic_mass: 140.908, number_of_neutrons: 82,
                    number_of_protons: 59, number_of_electrons: 59, period: 6, group: nil, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Lanthanide', atomic_radius: 2.7, electronegativity: 1.13,
                    first_ionization: 5.473, density: 6.77E+00, melting_point: 1204.15, boiling_point: 3793,
                    number_of_isotopes: 15, discoverer: 'von Welsbach', year: 1885,
                    specific_heat: 0.193, number_of_shells: 6, valence: nil },
          'Nd' => { atomic_number: 60, name: 'Neodymium', atomic_mass: 144.242, number_of_neutrons: 84,
                    number_of_protons: 60, number_of_electrons: 60, period: 6, group: nil, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Lanthanide', atomic_radius: 2.6, electronegativity: 1.14,
                    first_ionization: 5.525, density: 7.01E+00, melting_point: 1289.15, boiling_point: 3347,
                    number_of_isotopes: 16, discoverer: 'von Welsbach', year: 1885,
                    specific_heat: 0.19, number_of_shells: 6, valence: nil },
          'Pm' => { atomic_number: 61, name: 'Promethium', atomic_mass: 145, number_of_neutrons: 84,
                    number_of_protons: 61, number_of_electrons: 61, period: 6, group: nil, phase: 'artificial',
                    radioactive: true, natural: false, metal: true, nonmetal: false, metalloid: false,
                    type: 'Lanthanide', atomic_radius: 2.6, electronegativity: 1.13,
                    first_ionization: 5.582, density: 7.26E+00, melting_point: 1204.15, boiling_point: 3273,
                    number_of_isotopes: 14, discoverer: 'Marinsky et al.', year: 1945,
                    specific_heat: nil, number_of_shells: 6, valence: nil },
          'Sm' => { atomic_number: 62, name: 'Samarium', atomic_mass: 150.36, number_of_neutrons: 88,
                    number_of_protons: 62, number_of_electrons: 62, period: 6, group: nil, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Lanthanide', atomic_radius: 2.6, electronegativity: 1.17,
                    first_ionization: 5.6437, density: 7.52E+00, melting_point: 1345.15, boiling_point: 2067,
                    number_of_isotopes: 17, discoverer: 'Boisbaudran', year: 1879,
                    specific_heat: 0.197, number_of_shells: 6, valence: nil },
          'Eu' => { atomic_number: 63, name: 'Europium', atomic_mass: 151.964, number_of_neutrons: 89,
                    number_of_protons: 63, number_of_electrons: 63, period: 6, group: nil, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Lanthanide', atomic_radius: 2.6, electronegativity: 1.2,
                    first_ionization: 5.6704, density: 5.24E+00, melting_point: 1095.15, boiling_point: 1802,
                    number_of_isotopes: 21, discoverer: 'Demarcay', year: 1901,
                    specific_heat: 0.182, number_of_shells: 6, valence: nil },
          'Gd' => { atomic_number: 64, name: 'Gadolinium', atomic_mass: 157.25, number_of_neutrons: 93,
                    number_of_protons: 64, number_of_electrons: 64, period: 6, group: nil, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Lanthanide', atomic_radius: 2.5, electronegativity: 1.2,
                    first_ionization: 6.1501, density: 7.90E+00, melting_point: 1585.15, boiling_point: 3546,
                    number_of_isotopes: 17, discoverer: 'de Marignac', year: 1880,
                    specific_heat: 0.236, number_of_shells: 6, valence: nil },
          'Tb' => { atomic_number: 65, name: 'Terbium', atomic_mass: 158.925, number_of_neutrons: 94,
                    number_of_protons: 65, number_of_electrons: 65, period: 6, group: nil, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Lanthanide', atomic_radius: 2.5, electronegativity: 1.2,
                    first_ionization: 5.8638, density: 8.23E+00, melting_point: 1630.15, boiling_point: 3503,
                    number_of_isotopes: 24, discoverer: 'Mosander', year: 1843,
                    specific_heat: 0.182, number_of_shells: 6, valence: nil },
          'Dy' => { atomic_number: 66, name: 'Dysprosium', atomic_mass: 162.5, number_of_neutrons: 97,
                    number_of_protons: 66, number_of_electrons: 66, period: 6, group: nil, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Lanthanide', atomic_radius: 2.5, electronegativity: 1.22,
                    first_ionization: 5.9389, density: 8.55E+00, melting_point: 1680.15, boiling_point: 2840,
                    number_of_isotopes: 21, discoverer: 'de Boisbaudran', year: 1886,
                    specific_heat: 0.17, number_of_shells: 6, valence: nil },
          'Ho' => { atomic_number: 67, name: 'Holmium', atomic_mass: 164.93, number_of_neutrons: 98,
                    number_of_protons: 67, number_of_electrons: 67, period: 6, group: nil, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Lanthanide', atomic_radius: 2.5, electronegativity: 1.23,
                    first_ionization: 6.0215, density: 8.80E+00, melting_point: 1743.15, boiling_point: 2993,
                    number_of_isotopes: 29, discoverer: 'Delafontaine and Soret', year: 1878,
                    specific_heat: 0.165, number_of_shells: 6, valence: nil },
          'Er' => { atomic_number: 68, name: 'Erbium', atomic_mass: 167.259, number_of_neutrons: 99,
                    number_of_protons: 68, number_of_electrons: 68, period: 6, group: nil, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Lanthanide', atomic_radius: 2.5, electronegativity: 1.24,
                    first_ionization: 6.1077, density: 9.07E+00, melting_point: 1795.15, boiling_point: 3503,
                    number_of_isotopes: 16, discoverer: 'Mosander', year: 1843,
                    specific_heat: 0.168, number_of_shells: 6, valence: nil },
          'Tm' => { atomic_number: 69, name: 'Thulium', atomic_mass: 168.934, number_of_neutrons: 100,
                    number_of_protons: 69, number_of_electrons: 69, period: 6, group: nil, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Lanthanide', atomic_radius: 2.4, electronegativity: 1.25,
                    first_ionization: 6.1843, density: 9.32E+00, melting_point: 1818.15, boiling_point: 2223,
                    number_of_isotopes: 18, discoverer: 'Cleve', year: 1879,
                    specific_heat: 0.16, number_of_shells: 6, valence: nil },
          'Yb' => { atomic_number: 70, name: 'Ytterbium', atomic_mass: 173.054, number_of_neutrons: 103,
                    number_of_protons: 70, number_of_electrons: 70, period: 6, group: nil, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Lanthanide', atomic_radius: 2.4, electronegativity: 1.1,
                    first_ionization: 6.2542, density: 6.97E+00, melting_point: 1097.15, boiling_point: 1469,
                    number_of_isotopes: 16, discoverer: 'Marignac', year: 1878,
                    specific_heat: 0.155, number_of_shells: 6, valence: nil },
          'Lu' => { atomic_number: 71, name: 'Lutetium', atomic_mass: 174.967, number_of_neutrons: 104,
                    number_of_protons: 71, number_of_electrons: 71, period: 6, group: nil, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Lanthanide', atomic_radius: 2.3, electronegativity: 1.27,
                    first_ionization: 5.4259, density: 9.84E+00, melting_point: 1936.15, boiling_point: 3675,
                    number_of_isotopes: 22, discoverer: 'Urbain/ von Welsbach', year: 1907,
                    specific_heat: 0.154, number_of_shells: 6, valence: nil },
          'Hf' => { atomic_number: 72, name: 'Hafnium', atomic_mass: 178.49, number_of_neutrons: 106,
                    number_of_protons: 72, number_of_electrons: 72, period: 6, group: 4, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Transition Metal', atomic_radius: 2.2, electronegativity: 1.3,
                    first_ionization: 6.8251, density: 1.33E+01, melting_point: 2500.15, boiling_point: 4876,
                    number_of_isotopes: 17, discoverer: 'Coster and von Hevesy', year: 1923,
                    specific_heat: 0.144, number_of_shells: 6, valence: nil },
          'Ta' => { atomic_number: 73, name: 'Tantalum', atomic_mass: 180.948, number_of_neutrons: 108,
                    number_of_protons: 73, number_of_electrons: 73, period: 6, group: 5, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Transition Metal', atomic_radius: 2.1, electronegativity: 1.5,
                    first_ionization: 7.5496, density: 1.67E+01, melting_point: 3269.15, boiling_point: 5731,
                    number_of_isotopes: 19, discoverer: 'Ekeberg', year: 1801,
                    specific_heat: 0.14, number_of_shells: 6, valence: nil },
          'W' => { atomic_number: 74, name: 'Wolfram', atomic_mass: 183.84, number_of_neutrons: 110,
                   number_of_protons: 74, number_of_electrons: 74, period: 6, group: 6, phase: 'solid',
                   radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                   type: 'Transition Metal', atomic_radius: 2, electronegativity: 2.36,
                   first_ionization: 7.864, density: 1.93E+01, melting_point: 3680.15, boiling_point: 5828,
                   number_of_isotopes: 22, discoverer: "J. and F. d'Elhuyar", year: 1783,
                   specific_heat: 0.132, number_of_shells: 6, valence: nil },
          'Re' => { atomic_number: 75, name: 'Rhenium', atomic_mass: 186.207, number_of_neutrons: 111,
                    number_of_protons: 75, number_of_electrons: 75, period: 6, group: 7, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Transition Metal', atomic_radius: 2, electronegativity: 1.9,
                    first_ionization: 7.8335, density: 2.10E+01, melting_point: 3453.15, boiling_point: 5869,
                    number_of_isotopes: 21, discoverer: 'Noddack+Berg+Tacke', year: 1925,
                    specific_heat: 0.137, number_of_shells: 6, valence: nil },
          'Os' => { atomic_number: 76, name: 'Osmium', atomic_mass: 190.23, number_of_neutrons: 114,
                    number_of_protons: 76, number_of_electrons: 76, period: 6, group: 8, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Transition Metal', atomic_radius: 1.9, electronegativity: 2.2,
                    first_ionization: 8.4382, density: 2.26E+01, melting_point: 3300.15, boiling_point: 5285,
                    number_of_isotopes: 19, discoverer: 'Tennant', year: 1803,
                    specific_heat: 0.13, number_of_shells: 6, valence: nil },
          'Ir' => { atomic_number: 77, name: 'Iridium', atomic_mass: 192.217, number_of_neutrons: 115,
                    number_of_protons: 77, number_of_electrons: 77, period: 6, group: 9, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Transition Metal', atomic_radius: 1.9, electronegativity: 2.2,
                    first_ionization: 8.967, density: 2.26E+01, melting_point: 2716.15, boiling_point: 4701,
                    number_of_isotopes: 25, discoverer: 'Tennant', year: 1804,
                    specific_heat: 0.131, number_of_shells: 6, valence: nil },
          'Pt' => { atomic_number: 78, name: 'Platinum', atomic_mass: 195.084, number_of_neutrons: 117,
                    number_of_protons: 78, number_of_electrons: 78, period: 6, group: 10, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Transition Metal', atomic_radius: 1.8, electronegativity: 2.28,
                    first_ionization: 8.9587, density: 2.15E+01, melting_point: 2045.15, boiling_point: 4098,
                    number_of_isotopes: 32, discoverer: 'Ulloa/Wood', year: 1735,
                    specific_heat: 0.133, number_of_shells: 6, valence: nil },
          'Au' => { atomic_number: 79, name: 'Gold', atomic_mass: 196.967, number_of_neutrons: 118,
                    number_of_protons: 79, number_of_electrons: 79, period: 6, group: 11, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Transition Metal', atomic_radius: 1.8, electronegativity: 2.54,
                    first_ionization: 9.2255, density: 1.93E+01, melting_point: 1337.73, boiling_point: 3129,
                    number_of_isotopes: 21, discoverer: 'Prehistoric', year: nil,
                    specific_heat: 0.129, number_of_shells: 6, valence: nil },
          'Hg' => { atomic_number: 80, name: 'Mercury', atomic_mass: 200.59, number_of_neutrons: 121,
                    number_of_protons: 80, number_of_electrons: 80, period: 6, group: 12, phase: 'liq',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Transition Metal', atomic_radius: 1.8, electronegativity: 2,
                    first_ionization: 10.4375, density: 1.35E+01, melting_point: 234.43, boiling_point: 630,
                    number_of_isotopes: 26, discoverer: 'Prehistoric', year: nil,
                    specific_heat: 0.14, number_of_shells: 6, valence: nil },
          'Tl' => { atomic_number: 81, name: 'Thallium', atomic_mass: 204.383, number_of_neutrons: 123,
                    number_of_protons: 81, number_of_electrons: 81, period: 6, group: 13, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Metal', atomic_radius: 2.1, electronegativity: 2.04,
                    first_ionization: 6.1082, density: 1.19E+01, melting_point: 577.15, boiling_point: 1746,
                    number_of_isotopes: 28, discoverer: 'Crookes', year: 1861,
                    specific_heat: 0.129, number_of_shells: 6, valence: 3 },
          'Pb' => { atomic_number: 82, name: 'Lead', atomic_mass: 207.2, number_of_neutrons: 125,
                    number_of_protons: 82, number_of_electrons: 82, period: 6, group: 14, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Metal', atomic_radius: 1.8, electronegativity: 2.33,
                    first_ionization: 7.4167, density: 1.13E+01, melting_point: 600.75, boiling_point: 2022,
                    number_of_isotopes: 29, discoverer: 'Prehistoric', year: nil,
                    specific_heat: 0.129, number_of_shells: 6, valence: 4 },
          'Bi' => { atomic_number: 83, name: 'Bismuth', atomic_mass: 208.98, number_of_neutrons: 126,
                    number_of_protons: 83, number_of_electrons: 83, period: 6, group: 15, phase: 'solid',
                    radioactive: false, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Metal', atomic_radius: 1.6, electronegativity: 2.02,
                    first_ionization: 7.2856, density: 9.81E+00, melting_point: 544.67, boiling_point: 1837,
                    number_of_isotopes: 19, discoverer: 'Geoffroy the Younger', year: 1753,
                    specific_heat: 0.122, number_of_shells: 6, valence: 5 },
          'Po' => { atomic_number: 84, name: 'Polonium', atomic_mass: 210, number_of_neutrons: 126,
                    number_of_protons: 84, number_of_electrons: 84, period: 6, group: 16, phase: 'solid',
                    radioactive: true, natural: true, metal: false, nonmetal: false, metalloid: true,
                    type: 'Metalloid', atomic_radius: 1.5, electronegativity: 2,
                    first_ionization: 8.417, density: 9.32E+00, melting_point: 527.15, boiling_point: 1235,
                    number_of_isotopes: 34, discoverer: 'Curie', year: 1898,
                    specific_heat: nil, number_of_shells: 6, valence: 6 },
          'At' => { atomic_number: 85, name: 'Astatine', atomic_mass: 210, number_of_neutrons: 125,
                    number_of_protons: 85, number_of_electrons: 85, period: 6, group: 17, phase: 'solid',
                    radioactive: true, natural: true, metal: false, nonmetal: true, metalloid: false,
                    type: 'Noble Gas', atomic_radius: 1.4, electronegativity: 2.2,
                    first_ionization: 9.3, density: 7.00E+00, melting_point: 575.15, boiling_point: 610,
                    number_of_isotopes: 21, discoverer: 'Corson et al.', year: 1940,
                    specific_heat: nil, number_of_shells: 6, valence: 7 },
          'Rn' => { atomic_number: 86, name: 'Radon', atomic_mass: 222, number_of_neutrons: 136,
                    number_of_protons: 86, number_of_electrons: 86, period: 6, group: 18, phase: 'gas',
                    radioactive: true, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Alkali Metal', atomic_radius: 1.3, electronegativity: nil,
                    first_ionization: 10.7485, density: 9.73E-03, melting_point: 202.15, boiling_point: 211.3,
                    number_of_isotopes: 20, discoverer: 'Dorn', year: 1900,
                    specific_heat: 0.094, number_of_shells: 6, valence: 8 },
          'Fr' => { atomic_number: 87, name: 'Francium', atomic_mass: 223, number_of_neutrons: 136,
                    number_of_protons: 87, number_of_electrons: 87, period: 7, group: 1, phase: 'solid',
                    radioactive: true, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Alkaline Earth Metal', atomic_radius: nil, electronegativity: 0.7,
                    first_ionization: 4.0727, density: 1.87E+00, melting_point: 300.15, boiling_point: 950,
                    number_of_isotopes: 21, discoverer: 'Perey', year: 1939,
                    specific_heat: nil, number_of_shells: 7, valence: 1 },
          'Ra' => { atomic_number: 88, name: 'Radium', atomic_mass: 226, number_of_neutrons: 138,
                    number_of_protons: 88, number_of_electrons: 88, period: 7, group: 2, phase: 'solid',
                    radioactive: true, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Actinide', atomic_radius: nil, electronegativity: 0.9,
                    first_ionization: 5.2784, density: 5.50E+00, melting_point: 973.15, boiling_point: 2010,
                    number_of_isotopes: 15, discoverer: 'Pierre and Marie Curie', year: 1898,
                    specific_heat: nil, number_of_shells: 7, valence: 2 },
          'Ac' => { atomic_number: 89, name: 'Actinium', atomic_mass: 227, number_of_neutrons: 138,
                    number_of_protons: 89, number_of_electrons: 89, period: 7, group: 3, phase: 'solid',
                    radioactive: true, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Actinide', atomic_radius: nil, electronegativity: 1.1,
                    first_ionization: 5.17, density: 1.01E+01, melting_point: 1323.15, boiling_point: 3471,
                    number_of_isotopes: 11, discoverer: 'Debierne/Giesel', year: 1899,
                    specific_heat: 0.12, number_of_shells: 7, valence: nil },
          'Th' => { atomic_number: 90, name: 'Thorium', atomic_mass: 232.038, number_of_neutrons: 142,
                    number_of_protons: 90, number_of_electrons: 90, period: 7, group: nil, phase: 'solid',
                    radioactive: true, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Actinide', atomic_radius: nil, electronegativity: 1.3,
                    first_ionization: 6.3067, density: 1.17E+01, melting_point: 2028.15, boiling_point: 5061,
                    number_of_isotopes: 12, discoverer: 'Berzelius', year: 1828,
                    specific_heat: 0.113, number_of_shells: 7, valence: nil },
          'Pa' => { atomic_number: 91, name: 'Protactinium', atomic_mass: 231.036, number_of_neutrons: 140,
                    number_of_protons: 91, number_of_electrons: 91, period: 7, group: nil, phase: 'solid',
                    radioactive: true, natural: true, metal: true, nonmetal: false, metalloid: false,
                    type: 'Actinide', atomic_radius: nil, electronegativity: 1.5,
                    first_ionization: 5.89, density: 1.54E+01, melting_point: 1873.15, boiling_point: 4300,
                    number_of_isotopes: 14, discoverer: 'Hahn and Meitner', year: 1917,
                    specific_heat: nil, number_of_shells: 7, valence: nil },
          'U' => { atomic_number: 92, name: 'Uranium', atomic_mass: 238.029, number_of_neutrons: 146,
                   number_of_protons: 92, number_of_electrons: 92, period: 7, group: nil, phase: 'solid',
                   radioactive: true, natural: true, metal: true, nonmetal: false, metalloid: false,
                   type: 'Actinide', atomic_radius: nil, electronegativity: 1.38,
                   first_ionization: 6.1941, density: 1.90E+01, melting_point: 1405.15, boiling_point: 4404,
                   number_of_isotopes: 15, discoverer: 'Peligot', year: 1841,
                   specific_heat: 0.116, number_of_shells: 7, valence: nil },
          'Np' => { atomic_number: 93, name: 'Neptunium', atomic_mass: 237, number_of_neutrons: 144,
                    number_of_protons: 93, number_of_electrons: 93, period: 7, group: nil, phase: 'artificial',
                    radioactive: true, natural: false, metal: true, nonmetal: false, metalloid: false,
                    type: 'Actinide', atomic_radius: nil, electronegativity: 1.36,
                    first_ionization: 6.2657, density: 2.05E+01, melting_point: 913.15, boiling_point: 4273,
                    number_of_isotopes: 153, discoverer: 'McMillan and Abelson', year: 1940,
                    specific_heat: nil, number_of_shells: 7, valence: nil },
          'Pu' => { atomic_number: 94, name: 'Plutonium', atomic_mass: 244, number_of_neutrons: 150,
                    number_of_protons: 94, number_of_electrons: 94, period: 7, group: nil, phase: 'artificial',
                    radioactive: true, natural: false, metal: true, nonmetal: false, metalloid: false,
                    type: 'Actinide', atomic_radius: nil, electronegativity: 1.28,
                    first_ionization: 6.0262, density: 1.98E+01, melting_point: 913.15, boiling_point: 3501,
                    number_of_isotopes: 163, discoverer: 'Seaborg et al.', year: 1940,
                    specific_heat: nil, number_of_shells: 7, valence: nil },
          'Am' => { atomic_number: 95, name: 'Americium', atomic_mass: 243, number_of_neutrons: 148,
                    number_of_protons: 95, number_of_electrons: 95, period: 7, group: nil, phase: 'artificial',
                    radioactive: true, natural: false, metal: true, nonmetal: false, metalloid: false,
                    type: 'Actinide', atomic_radius: nil, electronegativity: 1.3,
                    first_ionization: 5.9738, density: 1.37E+01, melting_point: 1267.15, boiling_point: 2880,
                    number_of_isotopes: 133, discoverer: 'Seaborg et al.', year: 1944,
                    specific_heat: nil, number_of_shells: 7, valence: nil },
          'Cm' => { atomic_number: 96, name: 'Curium', atomic_mass: 247, number_of_neutrons: 151,
                    number_of_protons: 96, number_of_electrons: 96, period: 7, group: nil, phase: 'artificial',
                    radioactive: true, natural: false, metal: true, nonmetal: false, metalloid: false,
                    type: 'Actinide', atomic_radius: nil, electronegativity: 1.3,
                    first_ionization: 5.9915, density: 1.35E+01, melting_point: 1340.15, boiling_point: 3383,
                    number_of_isotopes: 133, discoverer: 'Seaborg et al.', year: 1944,
                    specific_heat: nil, number_of_shells: 7, valence: nil },
          'Bk' => { atomic_number: 97, name: 'Berkelium', atomic_mass: 247, number_of_neutrons: 150,
                    number_of_protons: 97, number_of_electrons: 97, period: 7, group: nil, phase: 'artificial',
                    radioactive: true, natural: false, metal: true, nonmetal: false, metalloid: false,
                    type: 'Actinide', atomic_radius: nil, electronegativity: 1.3,
                    first_ionization: 6.1979, density: 1.48E+01, melting_point: 1259.15, boiling_point: 983,
                    number_of_isotopes: 83, discoverer: 'Seaborg et al.', year: 1949,
                    specific_heat: nil, number_of_shells: 7, valence: nil },
          'Cf' => { atomic_number: 98, name: 'Californium', atomic_mass: 251, number_of_neutrons: 153,
                    number_of_protons: 98, number_of_electrons: 98, period: 7, group: nil, phase: 'artificial',
                    radioactive: true, natural: false, metal: true, nonmetal: false, metalloid: false,
                    type: 'Actinide', atomic_radius: nil, electronegativity: 1.3,
                    first_ionization: 6.2817, density: 1.51E+01, melting_point: 1925.15, boiling_point: 1173,
                    number_of_isotopes: 123, discoverer: 'Seaborg et al.', year: 1950,
                    specific_heat: nil, number_of_shells: 7, valence: nil },
          'Es' => { atomic_number: 99, name: 'Einsteinium', atomic_mass: 252, number_of_neutrons: 153,
                    number_of_protons: 99, number_of_electrons: 99, period: 7, group: nil, phase: 'artificial',
                    radioactive: true, natural: false, metal: true, nonmetal: false, metalloid: false,
                    type: 'Actinide', atomic_radius: nil, electronegativity: 1.3,
                    first_ionization: 6.42, density: 1.35E+01, melting_point: 1133.15, boiling_point: nil,
                    number_of_isotopes: 123, discoverer: 'Ghiorso et al.', year: 1952,
                    specific_heat: nil, number_of_shells: 7, valence: nil },
          'Fm' => { atomic_number: 100, name: 'Fermium', atomic_mass: 257, number_of_neutrons: 157,
                    number_of_protons: 100, number_of_electrons: 100, period: 7, group: nil, phase: 'artificial',
                    radioactive: true, natural: false, metal: true, nonmetal: false, metalloid: false,
                    type: 'Actinide', atomic_radius: nil, electronegativity: 1.3,
                    first_ionization: 6.5, density: nil, melting_point: nil, boiling_point: nil,
                    number_of_isotopes: 103, discoverer: 'Ghiorso et al.', year: 1953,
                    specific_heat: nil, number_of_shells: 7, valence: nil },
          'Md' => { atomic_number: 101, name: 'Mendelevium', atomic_mass: 258, number_of_neutrons: 157,
                    number_of_protons: 101, number_of_electrons: 101, period: 7, group: nil, phase: 'artificial',
                    radioactive: true, natural: false, metal: true, nonmetal: false, metalloid: false,
                    type: 'Actinide', atomic_radius: nil, electronegativity: 1.3,
                    first_ionization: 6.58, density: nil, melting_point: nil, boiling_point: nil,
                    number_of_isotopes: 33, discoverer: 'Ghiorso et al.', year: 1955,
                    specific_heat: nil, number_of_shells: 7, valence: nil },
          'No' => { atomic_number: 102, name: 'Nobelium', atomic_mass: 259, number_of_neutrons: 157,
                    number_of_protons: 102, number_of_electrons: 102, period: 7, group: nil, phase: 'artificial',
                    radioactive: true, natural: false, metal: true, nonmetal: false, metalloid: false,
                    type: 'Actinide', atomic_radius: nil, electronegativity: 1.3,
                    first_ionization: 6.65, density: nil, melting_point: nil, boiling_point: nil,
                    number_of_isotopes: 73, discoverer: 'Ghiorso et al.', year: 1958,
                    specific_heat: nil, number_of_shells: 7, valence: nil },
          'Lr' => { atomic_number: 103, name: 'Lawrencium', atomic_mass: 262, number_of_neutrons: 159,
                    number_of_protons: 103, number_of_electrons: 103, period: 7, group: nil, phase: 'artificial',
                    radioactive: true, natural: false, metal: true, nonmetal: false, metalloid: false,
                    type: 'Actinide', atomic_radius: nil, electronegativity: nil,
                    first_ionization: nil, density: nil, melting_point: nil, boiling_point: nil,
                    number_of_isotopes: 203, discoverer: 'Ghiorso et al.', year: 1961,
                    specific_heat: nil, number_of_shells: 7, valence: nil },
          'Rf' => { atomic_number: 104, name: 'Rutherfordium', atomic_mass: 261, number_of_neutrons: 157,
                    number_of_protons: 104, number_of_electrons: 104, period: 7, group: 4, phase: 'artificial',
                    radioactive: true, natural: false, metal: true, nonmetal: false, metalloid: false,
                    type: 'Transactinide', atomic_radius: nil, electronegativity: nil,
                    first_ionization: nil, density: 1.81E+01, melting_point: nil, boiling_point: nil,
                    number_of_isotopes: nil, discoverer: 'Ghiorso et al.', year: 1969,
                    specific_heat: nil, number_of_shells: 7, valence: nil },
          'Db' => { atomic_number: 105, name: 'Dubnium', atomic_mass: 262, number_of_neutrons: 157,
                    number_of_protons: 105, number_of_electrons: 105, period: 7, group: 5, phase: 'artificial',
                    radioactive: true, natural: false, metal: true, nonmetal: false, metalloid: false,
                    type: 'Transactinide', atomic_radius: nil, electronegativity: nil,
                    first_ionization: nil, density: 3.90E+01, melting_point: nil, boiling_point: nil,
                    number_of_isotopes: nil, discoverer: 'Ghiorso et al.', year: 1970,
                    specific_heat: nil, number_of_shells: 7, valence: nil },
          'Sg' => { atomic_number: 106, name: 'Seaborgium', atomic_mass: 266, number_of_neutrons: 160,
                    number_of_protons: 106, number_of_electrons: 106, period: 7, group: 6, phase: 'artificial',
                    radioactive: true, natural: false, metal: true, nonmetal: false, metalloid: false,
                    type: 'Transactinide', atomic_radius: nil, electronegativity: nil,
                    first_ionization: nil, density: 3.50E+01, melting_point: nil, boiling_point: nil,
                    number_of_isotopes: nil, discoverer: 'Ghiorso et al.', year: 1974,
                    specific_heat: nil, number_of_shells: 7, valence: nil },
          'Bh' => { atomic_number: 107, name: 'Bohrium', atomic_mass: 264, number_of_neutrons: 157,
                    number_of_protons: 107, number_of_electrons: 107, period: 7, group: 7, phase: 'artificial',
                    radioactive: true, natural: false, metal: true, nonmetal: false, metalloid: false,
                    type: 'Transactinide', atomic_radius: nil, electronegativity: nil,
                    first_ionization: nil, density: 3.70E+01, melting_point: nil, boiling_point: nil,
                    number_of_isotopes: nil, discoverer: 'Armbruster and M\xef\xbf\xbdnzenberg', year: 1981,
                    specific_heat: nil, number_of_shells: 7, valence: nil },
          'Hs' => { atomic_number: 108, name: 'Hassium', atomic_mass: 267, number_of_neutrons: 159,
                    number_of_protons: 108, number_of_electrons: 108, period: 7, group: 8, phase: 'artificial',
                    radioactive: true, natural: false, metal: true, nonmetal: false, metalloid: false,
                    type: 'Transactinide', atomic_radius: nil, electronegativity: nil,
                    first_ionization: nil, density: 4.10E+01, melting_point: nil, boiling_point: nil,
                    number_of_isotopes: nil, discoverer: 'Armbruster and M\xef\xbf\xbdnzenberg', year: 1983,
                    specific_heat: nil, number_of_shells: 7, valence: nil },
          'Mt' => { atomic_number: 109, name: 'Meitnerium', atomic_mass: 268, number_of_neutrons: 159,
                    number_of_protons: 109, number_of_electrons: 109, period: 7, group: 9, phase: 'artificial',
                    radioactive: true, natural: false, metal: true, nonmetal: false, metalloid: false,
                    type: 'Transactinide', atomic_radius: nil, electronegativity: nil,
                    first_ionization: nil, density: 3.50E+01, melting_point: nil, boiling_point: nil,
                    number_of_isotopes: nil, discoverer: 'GSI (Darmstadt West Germany)', year: 1982,
                    specific_heat: nil, number_of_shells: 7, valence: nil },
          'Ds' => { atomic_number: 110, name: 'Darmstadtium', atomic_mass: 271, number_of_neutrons: 161,
                    number_of_protons: 110, number_of_electrons: 110, period: 7, group: 10, phase: 'artificial',
                    radioactive: true, natural: false, metal: true, nonmetal: false, metalloid: false,
                    type: 'Transactinide', atomic_radius: nil, electronegativity: nil,
                    first_ionization: nil, density: nil, melting_point: nil, boiling_point: nil,
                    number_of_isotopes: nil, discoverer: nil, year: 1994,
                    specific_heat: nil, number_of_shells: 7, valence: nil },
          'Rg' => { atomic_number: 111, name: 'Roentgenium', atomic_mass: 272, number_of_neutrons: 161,
                    number_of_protons: 111, number_of_electrons: 111, period: 7, group: 11, phase: 'artificial',
                    radioactive: true, natural: false, metal: true, nonmetal: false, metalloid: false,
                    type: 'Transactinide', atomic_radius: nil, electronegativity: nil,
                    first_ionization: nil, density: nil, melting_point: nil, boiling_point: nil,
                    number_of_isotopes: nil, discoverer: nil, year: 1994,
                    specific_heat: nil, number_of_shells: 7, valence: nil },
          'Cn' => { atomic_number: 112, name: 'Copernicium', atomic_mass: 285, number_of_neutrons: 173,
                    number_of_protons: 112, number_of_electrons: 112, period: 7, group: 12, phase: 'artificial',
                    radioactive: true, natural: false, metal: true, nonmetal: false, metalloid: false,
                    type: 'Transactinide', atomic_radius: nil, electronegativity: nil,
                    first_ionization: nil, density: nil, melting_point: nil, boiling_point: nil,
                    number_of_isotopes: nil, discoverer: nil, year: 1996,
                    specific_heat: nil, number_of_shells: 7, valence: nil },
          'Nh' => { atomic_number: 113, name: 'Nihonium', atomic_mass: 284, number_of_neutrons: 171,
                    number_of_protons: 113, number_of_electrons: 113, period: 7, group: 13, phase: 'artificial',
                    radioactive: true, natural: false, metal: true, nonmetal: false, metalloid: false,
                    type: nil, atomic_radius: nil, electronegativity: nil,
                    first_ionization: nil, density: nil, melting_point: nil, boiling_point: nil,
                    number_of_isotopes: nil, discoverer: nil, year: 2004,
                    specific_heat: nil, number_of_shells: 7, valence: 3 },
          'Fl' => { atomic_number: 114, name: 'Flerovium', atomic_mass: 289, number_of_neutrons: 175,
                    number_of_protons: 114, number_of_electrons: 114, period: 7, group: 14, phase: 'artificial',
                    radioactive: true, natural: false, metal: true, nonmetal: false, metalloid: false,
                    type: 'Transactinide', atomic_radius: nil, electronegativity: nil,
                    first_ionization: nil, density: nil, melting_point: nil, boiling_point: nil,
                    number_of_isotopes: nil, discoverer: nil, year: 1999,
                    specific_heat: nil, number_of_shells: 7, valence: 4 },
          'Mc' => { atomic_number: 115, name: 'Moscovium', atomic_mass: 288, number_of_neutrons: 173,
                    number_of_protons: 115, number_of_electrons: 115, period: 7, group: 15, phase: 'artificial',
                    radioactive: true, natural: false, metal: true, nonmetal: false, metalloid: false,
                    type: nil, atomic_radius: nil, electronegativity: nil,
                    first_ionization: nil, density: nil, melting_point: nil, boiling_point: nil,
                    number_of_isotopes: nil, discoverer: nil, year: 2010,
                    specific_heat: nil, number_of_shells: 7, valence: 5 },
          'Lv' => { atomic_number: 116, name: 'Livermorium', atomic_mass: 292, number_of_neutrons: 176,
                    number_of_protons: 116, number_of_electrons: 116, period: 7, group: 16, phase: 'artificial',
                    radioactive: true, natural: false, metal: true, nonmetal: false, metalloid: false,
                    type: 'Transactinide', atomic_radius: nil, electronegativity: nil,
                    first_ionization: nil, density: nil, melting_point: nil, boiling_point: nil,
                    number_of_isotopes: nil, discoverer: nil, year: 2000,
                    specific_heat: nil, number_of_shells: 7, valence: 6 },
          'Ts' => { atomic_number: 117, name: 'Tennessine', atomic_mass: 295, number_of_neutrons: 178,
                    number_of_protons: 117, number_of_electrons: 117, period: 7, group: 17, phase: 'artificial',
                    radioactive: true, natural: false, metal: false, nonmetal: true, metalloid: false,
                    type: nil, atomic_radius: nil, electronegativity: nil,
                    first_ionization: nil, density: nil, melting_point: nil, boiling_point: nil,
                    number_of_isotopes: nil, discoverer: nil, year: 2010,
                    specific_heat: nil, number_of_shells: 7, valence: 7 },
          'Og' => { atomic_number: 118, name: 'Oganesson', atomic_mass: 294, number_of_neutrons: 176,
                    number_of_protons: 118, number_of_electrons: 118, period: 7, group: 18, phase: 'artificial',
                    radioactive: true, natural: false, metal: false, nonmetal: true, metalloid: false,
                    type: 'Noble Gas', atomic_radius: nil, electronegativity: nil,
                    first_ionization: nil, density: nil, melting_point: nil, boiling_point: nil,
                    number_of_isotopes: nil, discoverer: nil, year: 2006,
                    specific_heat: nil, number_of_shells: 7, valence: 8 },
        },
      )
    end
  end
end
