A_AND_AS_LEVEL_SUBJECTS = [
  'Accounting',
  'Ancient History',
  'Anthropology',
  'Applied Art and Design',
  'Applied Art and Design (Double award)',
  'Applied Business',
  'Applied Business (Double award)',
  'Applied Information and Communication Technology',
  'Applied Information and Communication Technology (Double award)',
  'Applied Science',
  'Applied Science (Double award)',
  'Applied Welsh Second Language',
  'Arabic',
  'Arabic (listening, reading and writing)',
  'Archaeology',
  'Art and Design',
  'Bengali',
  'Biblical Hebrew',
  'Biology',
  'Biology (Salters-Nuffield)',
  'Biology A',
  'Biology A (Salters-Nuffield)',
  'Biology B',
  'Biology B (Advancing Biology)',
  'Biology and Biology (Human)',
  'Biology and Human Biology A',
  'Business',
  'Business Studies',
  'Chemistry',
  'Chemistry (Nuffield)',
  'Chemistry A',
  'Chemistry B',
  'Chemistry B (Salters)',
  'Chinese',
  'Chinese (spoken Mandarin/spoken Cantonese)',
  'Citizenship Studies',
  'Classical Civilisation',
  'Classical Greek',
  'Classics',
  'Communication Studies',
  'Communication and Culture',
  'Computer Science',
  'Computing',
  'Creative Writing',
  'Critical Thinking',
  'Cymraeg Ail Iaith',
  'Cymraeg Iaith Gyntaf',
  'Dance',
  'Design and Technology',
  'Design and Technology (Design Engineering/Fashion and Textiles/Product Design)',
  'Design and Technology (Fashion and Textiles/Product Design)',
  'Design and Technology: Fashion and Textiles',
  'Design and Technology: Food Technology',
  'Design and Technology: Product Design',
  'Design and Technology: Product Design (3-D Design)',
  'Design and Technology: Product Design (Textiles)',
  'Design and Technology: Systems and Control Technology',
  'Digital Technology',
  'Drama and Theatre',
  'Drama and Theatre Studies',
  'Dutch',
  'Economics',
  'Economics A',
  'Economics B',
  'Economics and Business',
  'Economics and Business Studies (Nuffield)',
  'Electronics',
  'Engineering',
  'English Language',
  'English Language A',
  'English Language B',
  'English Language and Literature',
  'English Language and Literature (EMC)',
  'English Language and Literature A',
  'English Language and Literature B',
  'English Literature',
  'English Literature A',
  'English Literature B',
  'Environmental Science',
  'Environmental Studies',
  'Environmental Technology',
  'European Studies',
  'Film Studies',
  'French',
  'Further Mathematics',
  'Further Mathematics (MEI)',
  'Further Mathematics A',
  'Further Mathematics B (MEI)',
  'General Studies',
  'General Studies A',
  'General Studies B',
  'Geography',
  'Geography A',
  'Geography B',
  'Geology',
  'German',
  'Government and Politics',
  'Greek',
  'Greek (listening, reading and writing)',
  'Gujarati',
  'Gujarati (listening, reading and writing)',
  'Health and Social Care',
  'Health and Social Care (Double award)',
  'History',
  'History A',
  'History B',
  'History of Art',
  'History of Art and Design',
  'History, Philosophy and Ethics of Science',
  'Home Economics',
  'Home Economics (Food, Nutrition and Health)',
  'Human Biology',
  'Humanities',
  'Information and Communication Technology',
  'Irish',
  'Italian',
  'Japanese',
  'Japanese (listening, reading and writing)',
  'Journalism in the Media and Communications Industry',
  'Latin',
  'Law',
  'Leisure Studies',
  'Leisure Studies (Double award)',
  'Life and Health Sciences',
  'Life and Health Sciences (Double award)',
  'Mathematics',
  'Mathematics (MEI)',
  'Mathematics A',
  'Mathematics B',
  'Mathematics B (MEI)',
  'Media Studies',
  'Media: Communication and Production',
  'Modern Greek',
  'Modern Hebrew',
  'Moving Image Arts',
  'Music',
  'Music Technology',
  'Nutrition and Food Science',
  'Panjabi',
  'Performance Studies',
  'Performing Arts',
  'Persian',
  'Persian (listening, reading and writing)',
  'Philosophy',
  'Physical Education',
  'Physics',
  'Physics (Salters Horners)',
  'Physics A',
  'Physics B',
  'Physics B (Advancing Physics)',
  'Physics B: Physics in Context',
  'Polish',
  'Politics',
  'Portuguese',
  'Portuguese (listening, reading and writing)',
  'Professional Business Services',
  'Psychology',
  'Psychology A',
  'Psychology B',
  'Pure Mathematics',
  'Pure Mathematics (MEI)',
  'Religious Studies',
  'Russian',
  'Science',
  'Science for Public Understanding',
  'Science in Society',
  'Social Policy',
  'Social Science: Citizenship',
  'Sociology',
  'Software Systems Development',
  'Spanish',
  'Sport and Physical Education',
  'Sports Science and the Active Leisure Industry',
  'Statistics',
  'Statistics (MEI)',
  'Technology and Design',
  'Technology and Design: Systems and Control',
  'Travel and Tourism',
  'Travel and Tourism (Double award)',
  'Turkish',
  'Turkish (listening, reading and writing)',
  'Urdu',
  'Urdu (listening, reading and writing)',
  'Use of Mathematics',
  'World Development',
].freeze
