HESA_DEGREE_TYPES = [
  ['51', 'BA', 'Bachelor of Arts', :bachelor],
  ['52', 'BAEcon', 'Bachelor of Arts Economics', :bachelor],
  ['53', 'BAArch', 'Bachelor of Arts in Architecture', :bachelor],
  ['54', 'BAO', 'Bachelor of the Art of Obstetrics', :bachelor],
  ['55', 'BAArch', 'Bachelor of Architecture', :bachelor],
  ['56', 'BAsc', 'Bachelor of Applied Science', :bachelor],
  ['57', 'BAg', 'Bachelor of Agriculture', :bachelor],
  ['58', 'BAcc', 'Bachelor of Accountancy', :bachelor],
  ['59', 'BAdmin', 'Bachelor of Administration', :bachelor],
  ['60', 'BBA', 'Bachelor of Business Administration', :bachelor],
  ['61', 'BCS', 'Bachelor of Combined Studies', :bachelor],
  ['62', 'BComm', 'Bachelor of Commerce', :bachelor],
  ['63', 'BD', 'Bachelor of Divinity', :bachelor],
  ['64', 'BDS', 'Bachelor of Dental Surgery', :bachelor],
  ['65', 'BEng', 'Bachelor of Engineering', :bachelor],
  ['66', 'BEng/BS', 'Bachelor of Engineering with Business Studies', :bachelor],
  ['67', 'BFA', 'Bachelor of Fine Art', :bachelor],
  ['68', 'BGS', 'Bachelor of General Studies', :bachelor],
  ['69', 'BH', 'Bachelor of Humanities', :bachelor],
  ['70', 'BHyg', 'Bachelor of Hygiene', :bachelor],
  ['71', 'LLB', 'Bachelor of Law', :bachelor],
  ['72', 'BLib', 'Bachelor of Librarianship', :bachelor],
  ['73', 'BLS', 'Bachelor of Librarianship and Information Studies', :bachelor],
  ['74', 'BLitt', 'Bachelor of Literature', :bachelor],
  ['75', 'BLEcon', 'Bachelor of Land Economy', :bachelor],
  ['76', 'BMedSc', 'Bachelor of Medical Science', :bachelor],
  ['77', 'BM', 'Bachelor of Medicine', :bachelor],
  ['78', 'BMet', 'Bachelor of Metallurgy', :bachelor],
  ['79', 'BMet/Eng', 'Bachelor of Metallurgy and Engineering', :bachelor],
  ['80', 'BMu', 'Bachelor of Music', :bachelor],
  ['81', 'BN', 'Bachelor of Nursing', :bachelor],
  ['82', 'BPharm', 'Bachelor of Pharmacy', :bachelor],
  ['83', 'BSc', 'Bachelor of Science', :bachelor],
  ['84', 'BSc (Econ)', 'Bachelor of Science Economics', :bachelor],
  ['85', 'BSc (Eng)', 'Bachelor of Science and Engineering', :bachelor],
  ['86', 'BSc (Tech)', 'Bachelor of Science and Technology', :bachelor],
  ['87', 'BSc SS', 'Bachelor of Science in Social Science', :bachelor],
  ['88', 'BSc SPT', 'Bachelor of Science in Speech Therapy', :bachelor],
  ['89', 'BSS', 'Bachelor of Social Science', :bachelor],
  ['90', 'BS', 'Bachelor of Surgery', :bachelor],
  ['91', 'BCh', 'Bachelor of Chirurgiae', :bachelor],
  ['92', 'BTech', 'Bachelor of Technology', :bachelor],
  ['93', 'BTheol', 'Bachelor of Theology', :bachelor],
  ['94', 'BVMed', 'Bachelor of Veterinary Medicine', :bachelor],
  ['95', 'BVMS', 'Bachelor of Veterinary Medicine and Surgery', :bachelor],
  ['96', 'BVsc', 'Bachelor of Veterinary Science', :bachelor],
  ['97', 'BEd', 'Bachelor of Education Scotland and Northern Ireland', :bachelor],
  ['98', 'BPhil', 'Bachelor of Philosophy', :bachelor],

  ['1', nil, 'BEd', :bachelor],
  ['3', nil, 'BSc/Education', :bachelor],
  ['5', nil, 'BTech/Education', :bachelor],
  ['7', nil, 'BA/Education', :bachelor],
  ['9', nil, 'BA Combined Studies/Education of the Deaf', :bachelor],
  ['12', nil, 'BA with intercalated PGCE', :bachelor],

  ['200', 'MA', 'Master of Arts', :master],
  ['201', 'MLib', 'Master of Librarianship', :master],
  ['202', 'MLitt', 'Master of Literature', :master],
  ['203', 'MMus', 'Master of Music', :master],
  ['204', 'MPhil', 'Master of Philosophy', :master],
  ['205', 'MSc', 'Master of Science', :master],
  ['206', 'MTheol', 'Master of Theology', :master],
  ['207', nil, 'Certificate of Membership of Cranfield Institute of Technology', :master],
  ['208', 'MEd', 'Master of Education', :master],
  ['209', 'MBS', 'Master of Business Studies', :master],
  ['210', 'MSS', 'Master of Social Studies', :master],
  ['211', 'MEng', 'Master of Engineering', :master],
  ['212', 'MLaw', 'Master of Law', :master],
  ['213', 'MBA', 'Master of Business Administration', :master],
  ['214', 'MChem', 'Master of Chemistry', :master],
  ['215', 'MPhys', 'Master of Physics', :master],

  ['300', 'DD', 'Doctor of Divinity', :doctor],
  ['301', 'DCL', 'Doctor of Civil Law', :doctor],
  ['302', 'MD', 'Doctor of Medicine', :doctor],
  ['303', 'DMu', 'Doctor of Music', :doctor],
  ['304', 'DSc', 'Doctor of Science', :doctor],
  ['305', 'DPhil', 'Doctor of Philosophy', :doctor],
  ['306', nil, 'PhD', :doctor],

  ['400', nil, 'First Degree', :other],
  ['401', nil, 'Higher Degree', :other],
  ['402', nil, 'Degree equivalent', :other],
].freeze
