HESA_DEGREE_GRADES = [
  ['1', 'First class honours', :main_undergrad],
  ['2', 'Upper second-class honours (2:1)', :main_undergrad],
  ['3', 'Lower second-class honours (2:2)', :main_undergrad],
  ['4', 'Undivided second class honours', :other],
  ['5', 'Third-class honours', :main_undergrad],
  ['6', 'Fourth class honours', :other],
  ['7', 'Unclassified', :other],
  ['8', 'Aegrotat', :other],
  ['10', 'Ordinary degree', :other],
  ['11', 'General degree', :other],
  ['12', 'Distinction', :main_postgrad],
  ['13', 'Merit', :main_postgrad],
  ['14', 'Pass', :main_undergrad],
  ['98', 'Not applicable', :main_postgrad],
  ['99', 'Unknown', :main_postgrad],
].freeze
