# rubocop:disable Style/WordArray
HESA_DEGREE_INSTITUTIONS = [
  ['1', 'The Open University'],
  ['2', 'Cranfield University'],
  ['3', 'Royal College of Art'],
  ['4', 'The College of Guidance Studies'],
  ['6', 'The Royal College of Nursing'],
  ['7', 'Bishop Grosseteste University'],
  ['8', 'Bretton Hall College of HE'],
  ['9', 'Buckinghamshire New University'],
  ['10', 'The Royal Central School of Speech and Drama'],
  ['11', 'University of Chester'],
  ['12', 'Canterbury Christ Church University'],
  ['13', 'York St John University'],
  ['14', 'University of St Mark and St John'],
  ['15', 'Dartington College of Arts'],
  ['16', 'Edge Hill University'],
  ['17', 'Falmouth University'],
  ['18', 'Harper Adams University'],
  ['19', 'Homerton College'],
  ['20', 'Kent Institute of Art and Design'],
  ['21', 'The University of Winchester'],
  ['22', 'La Sainte Union College of HE'],
  ['23', 'Liverpool Hope University'],
  ['24', 'University of the Arts, London'],
  ['25', 'Loughborough College of Art and Design'],
  ['26', 'University of Bedfordshire'],
  ['27', 'The University of Northampton'],
  ['28', 'Newman University'],
  ['29', 'North Riding College Higher Education Corporation'],
  ['30', 'Ravensbourne'],
  ['31', 'Roehampton University'],
  ['32', 'Rose Bruford College'],
  ['33', 'Royal Academy of Music'],
  ['34', 'Royal College of Music'],
  ['35', 'Royal Northern College of Music'],
  ['36', 'Salford College of Technology'],
  ['37', 'Southampton Solent University'],
  ['38', 'University of Cumbria'],
  ['39', "St Mary's University, Twickenham"],
  ['40', 'Leeds Trinity University'],
  ['41', 'Trinity Laban Conservatoire of Music and Dance'],
  ['42', 'Westminster College'],
  ['43', 'West London Institute of HE'],
  ['44', 'The Surrey Institute of Art and Design, University College'],
  ['45', 'Winchester School of Art'],
  ['46', 'University of Worcester'],
  ['47', 'Anglia Ruskin University'],
  ['48', 'Bath Spa University'],
  ['49', 'The University of Bolton'],
  ['50', 'Bournemouth University'],
  ['51', 'The University of Brighton'],
  ['52', 'Birmingham City University'],
  ['53', 'The University of Central Lancashire'],
  ['54', 'University of Gloucestershire'],
  ['55', 'London Guildhall University'],
  ['56', 'Coventry University'],
  ['57', 'University of Derby'],
  ['58', 'The University of East London'],
  ['59', 'The University of Greenwich'],
  ['60', 'University of Hertfordshire'],
  ['61', 'The University of Huddersfield'],
  ['62', 'The University of Lincoln'],
  ['63', 'Kingston University'],
  ['64', 'Leeds Beckett University'],
  ['65', 'Liverpool John Moores University'],
  ['66', 'The Manchester Metropolitan University'],
  ['67', 'Middlesex University'],
  ['68', 'De Montfort University'],
  ['69', 'University of Northumbria at Newcastle'],
  ['70', 'The University of North London'],
  ['71', 'The Nottingham Trent University'],
  ['72', 'Oxford Brookes University'],
  ['73', 'University of Plymouth'],
  ['74', 'The University of Portsmouth'],
  ['75', 'Sheffield Hallam University'],
  ['76', 'London South Bank University'],
  ['77', 'Staffordshire University'],
  ['78', 'The University of Sunderland'],
  ['79', 'Teesside University'],
  ['80', 'The University of West London'],
  ['81', 'University of the West of England, Bristol'],
  ['82', 'The University of Chichester'],
  ['83', 'The University of Westminster'],
  ['84', 'Wimbledon School of Art'],
  ['85', 'The University of Wolverhampton'],
  ['86', 'The University of Wales, Newport'],
  ['87', 'Glyndŵr University'],
  ['88', 'Coleg Normal'],
  ['89', 'Cardiff Metropolitan University'],
  ['90', 'University of South Wales'],
  ['91', 'Swansea Metropolitan University'],
  ['92', 'Trinity University College'],
  ['94', 'Duncan of Jordanstone College of Art'],
  ['95', 'University of Abertay Dundee'],
  ['96', 'Edinburgh College of Art'],
  ['97', 'Glasgow School of Art'],
  ['98', 'Moray House Institute of Education'],
  ['99', 'Northern College of Education'],
  ['100', 'Queen Margaret University, Edinburgh'],
  ['101', 'Royal Conservatoire of Scotland'],
  ['102', "St Andrew's College of Education"],
  ['103', 'The Scottish College of Textiles'],
  ['104', 'The Robert Gordon University'],
  ['105', 'The University of the West of Scotland'],
  ['106', 'Glasgow Caledonian University'],
  ['107', 'Edinburgh Napier University'],
  ['108', 'Aston University'],
  ['109', 'The University of Bath'],
  ['110', 'The University of Birmingham'],
  ['111', 'The University of Bradford'],
  ['112', 'The University of Bristol'],
  ['113', 'Brunel University London'],
  ['114', 'The University of Cambridge'],
  ['115', 'City, University of London'],
  ['116', 'University of Durham'],
  ['117', 'The University of East Anglia'],
  ['118', 'The University of Essex'],
  ['119', 'The University of Exeter'],
  ['120', 'The University of Hull'],
  ['121', 'The University of Keele'],
  ['122', 'The University of Kent'],
  ['123', 'The University of Lancaster'],
  ['124', 'The University of Leeds'],
  ['125', 'The University of Leicester'],
  ['126', 'The University of Liverpool'],
  ['127', 'Birkbeck College'],
  ['128', 'British Postgraduate Medical Federation'],
  ['129', 'Charing Cross and Westminster Medical School'],
  ['131', 'Goldsmiths College'],
  ['132', 'Imperial College of Science, Technology and Medicine'],
  ['133', 'Institute of Education'],
  ['134', "King's College London"],
  ['135', 'London Business School'],
  ['136', 'The London Hospital Medical College'],
  ['137', 'London School of Economics and Political Science'],
  ['138', 'London School of Hygiene and Tropical Medicine'],
  ['139', 'Queen Mary University of London'],
  ['140', 'Royal Free Hospital School of Medicine'],
  ['141', 'Royal Holloway and Bedford New College'],
  ['142', 'Royal Postgraduate Medical School'],
  ['143', 'The Royal Veterinary College'],
  ['144', "St Bartholomew's Hospital Medical College"],
  ['145', "St George's Hospital Medical School"],
  ['146', 'The School of Oriental and African Studies'],
  ['147', 'The School of Pharmacy'],
  ['148', "United Medical and Dental Schools, Guy's and St Thomas's Hospitals"],
  ['149', 'University College London'],
  ['150', 'Wye College'],
  ['151', 'University of London (Institutes and activities)'],
  ['152', 'Loughborough University'],
  ['153', 'The Victoria Manchester University'],
  ['154', 'University of Newcastle-upon-Tyne'],
  ['155', 'University of Nottingham'],
  ['156', 'The University of Oxford'],
  ['157', 'The University of Reading'],
  ['158', 'The University of Salford'],
  ['159', 'The University of Sheffield'],
  ['160', 'The University of Southampton'],
  ['161', 'The University of Surrey'],
  ['162', 'The University of Sussex'],
  ['163', 'The University of Warwick'],
  ['164', 'The University of York'],
  ['165', 'The University of Manchester Institute of Science and Technology'],
  ['167', 'The University of Edinburgh'],
  ['168', 'The University of Glasgow'],
  ['169', 'The University of Strathclyde'],
  ['170', 'The University of Aberdeen'],
  ['171', 'Heriot-Watt University'],
  ['172', 'The University of Dundee'],
  ['173', 'The University of St Andrews'],
  ['174', 'The University of Stirling'],
  ['175', 'SRUC'],
  ['176', 'University of Wales Trinity Saint David'],
  ['177', 'Aberystwyth University'],
  ['178', 'Bangor University'],
  ['179', 'Cardiff University'],
  ['180', 'Swansea University'],
  ['181', 'University of Wales College of Medicine'],
  ['182', 'Royal Welsh College of Music and Drama'],
  ['183', 'Welsh Agricultural College'],
  ['184', "The Queen's University of Belfast"],
  ['185', 'University of Ulster'],
  ['187', 'Westhill College'],
  ['188', 'The Institute of Cancer Research'],
  ['189', 'Writtle College'],
  ['190', 'Norwich University of the Arts'],
  ['191', 'Northern School of Contemporary Dance'],
  ['192', 'Cumbria Institute of the Arts'],
  ['193', 'Stranmillis University College'],
  ['194', "St Mary's University College"],
  ['195', 'Royal Agricultural University'],
  ['196', 'University of the Highlands and Islands'],
  ['197', 'The Arts University Bournemouth'],
  ['198', 'Bell College'],
  ['199', 'Conservatoire for Dance and Drama'],
  ['200', 'University College Birmingham'],
  ['201', 'Courtauld Institute of Art'],
  ['202', 'London Metropolitan University'],
  ['203', 'The University of Buckingham'],
  ['204', 'The University of Manchester'],
  ['205', 'Heythrop College'],
  ['206', 'University for the Creative Arts'],
  ['207', 'Leeds College of Music'],
  ['208', 'Guildhall School of Music and Drama'],
  ['209', 'The Liverpool Institute for Performing Arts'],
  ['210', 'University Campus Suffolk'],
  ['211', 'Leeds College of Art'],
  ['228', 'Liverpool School of Tropical Medicine'],
  ['229', 'The National Film and Television School'],
  ['230', 'Plymouth College of Art'],
  ['9065', 'Council for National Academic Awards'],
].freeze
# rubocop:enable Style/WordArray
