FactoryBot.define do
  factory :provider_edi_report, class: '::Publications::ProviderEdiReport' do
    provider
    recruitment_cycle_year { 2026 }
    cycle_week { 16 }
    generation_date { Time.zone.local(recruitment_cycle_year, 6, 1) }
    publication_date { Time.zone.local(recruitment_cycle_year, 6, 1) }
    category { :sex }

    transient do
      submitted_to_date { rand(100..100_00) }
      submitted_previous_cycle { rand(0..submitted_to_date) }

      offered_to_date { rand(0..submitted_to_date) }
      offered_previous_cycle { rand(0..submitted_previous_cycle) }

      accepted_to_date { rand(0..(submitted_to_date / 2)) }
      recruited_rate { accepted_to_date.to_f / submitted_to_date }

      accepted_last_cycle { rand(0..(submitted_previous_cycle / 2)) }
      recruited_rate_last_cycle { accepted_last_cycle.to_f / submitted_previous_cycle }
    end

    statistics do
      [
        {
          'nonprovider_filter' => 'Unknown',
          'nonprovider_filter_category' => 'Sex',
          'cycle_week' => cycle_week,
          'recruitment_cycle_year' => recruitment_cycle_year,
          'provider_id' => '1735',
          'number_of_candidates_submitted_to_date' => submitted_to_date,
          'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
          'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
          'number_of_candidates_with_offers_to_date' => rand(0..submitted_to_date),
          'number_of_candidates_with_offers_to_same_date_previous_cycle' => rand(0..submitted_previous_cycle),
          'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
          'offer_rate_to_date' => 0.0,
          'offer_rate_to_same_date_previous_cycle' => 0.25,
          'number_of_candidates_accepted_to_date' => accepted_to_date,
          'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
          'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
          'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
          'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
          'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
          'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
          'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
          'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
          'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
          'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
          'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
          'recruited_rate_to_date' => recruited_rate,
          'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
        },
        {
          'nonprovider_filter' => 'Other',
          'nonprovider_filter_category' => 'Sex',
          'cycle_week' => cycle_week,
          'recruitment_cycle_year' => recruitment_cycle_year,
          'provider_id' => '1735',
          'number_of_candidates_submitted_to_date' => submitted_to_date,
          'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
          'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
          'number_of_candidates_with_offers_to_date' => rand(0..submitted_to_date),
          'number_of_candidates_with_offers_to_same_date_previous_cycle' => rand(0..submitted_previous_cycle),
          'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
          'offer_rate_to_date' => 0.0,
          'offer_rate_to_same_date_previous_cycle' => 0.25,
          'number_of_candidates_accepted_to_date' => accepted_to_date,
          'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
          'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
          'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
          'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
          'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
          'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
          'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
          'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
          'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
          'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
          'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
          'recruited_rate_to_date' => recruited_rate,
          'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
        },
        {
          'nonprovider_filter' => 'Prefer not to say',
          'nonprovider_filter_category' => 'Sex',
          'cycle_week' => cycle_week,
          'recruitment_cycle_year' => recruitment_cycle_year,
          'provider_id' => '1735',
          'number_of_candidates_submitted_to_date' => submitted_to_date,
          'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
          'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
          'number_of_candidates_with_offers_to_date' => rand(0..submitted_to_date),
          'number_of_candidates_with_offers_to_same_date_previous_cycle' => rand(0..submitted_previous_cycle),
          'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
          'offer_rate_to_date' => 0.0,
          'offer_rate_to_same_date_previous_cycle' => 0.25,
          'number_of_candidates_accepted_to_date' => accepted_to_date,
          'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
          'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
          'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
          'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
          'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
          'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
          'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
          'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
          'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
          'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
          'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
          'recruited_rate_to_date' => recruited_rate,
          'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
        },
        {
          'nonprovider_filter' => 'Female',
          'nonprovider_filter_category' => 'Sex',
          'cycle_week' => cycle_week,
          'recruitment_cycle_year' => recruitment_cycle_year,
          'provider_id' => '1735',
          'number_of_candidates_submitted_to_date' => submitted_to_date,
          'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
          'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
          'number_of_candidates_with_offers_to_date' => rand(0..submitted_to_date),
          'number_of_candidates_with_offers_to_same_date_previous_cycle' => rand(0..submitted_previous_cycle),
          'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
          'offer_rate_to_date' => 0.0,
          'offer_rate_to_same_date_previous_cycle' => 0.25,
          'number_of_candidates_accepted_to_date' => accepted_to_date,
          'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
          'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
          'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
          'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
          'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
          'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
          'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
          'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
          'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
          'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
          'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
          'recruited_rate_to_date' => recruited_rate,
          'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
        },
        {
          'nonprovider_filter' => 'Male',
          'nonprovider_filter_category' => 'Sex',
          'cycle_week' => cycle_week,
          'recruitment_cycle_year' => recruitment_cycle_year,
          'provider_id' => '1735',
          'number_of_candidates_submitted_to_date' => submitted_to_date,
          'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
          'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
          'number_of_candidates_with_offers_to_date' => rand(0..submitted_to_date),
          'number_of_candidates_with_offers_to_same_date_previous_cycle' => rand(0..submitted_previous_cycle),
          'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
          'offer_rate_to_date' => 0.0,
          'offer_rate_to_same_date_previous_cycle' => 0.25,
          'number_of_candidates_accepted_to_date' => accepted_to_date,
          'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
          'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
          'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
          'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
          'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
          'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
          'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
          'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
          'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
          'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
          'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
          'recruited_rate_to_date' => recruited_rate,
          'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
        },
      ]
    end

    trait :disability do
      category { :disability }
      statistics do
        [
          {
            'nonprovider_filter' => 59,
            'nonprovider_filter_category' => 'HESA disability',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => '1735',
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => rand(0..submitted_to_date),
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => rand(0..submitted_previous_cycle),
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            'nonprovider_filter' => 58,
            'nonprovider_filter_category' => 'HESA disability',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => '1735',
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => rand(0..submitted_to_date),
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => rand(0..submitted_previous_cycle),
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            'nonprovider_filter' => 56,
            'nonprovider_filter_category' => 'HESA disability',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => '1735',
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => rand(0..submitted_to_date),
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => rand(0..submitted_previous_cycle),
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            'nonprovider_filter' => 57,
            'nonprovider_filter_category' => 'HESA disability',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => '1735',
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => rand(0..submitted_to_date),
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => rand(0..submitted_previous_cycle),
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            'nonprovider_filter' => 53,
            'nonprovider_filter_category' => 'HESA disability',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => '1735',
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => rand(0..submitted_to_date),
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => rand(0..submitted_previous_cycle),
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            'nonprovider_filter' => 96,
            'nonprovider_filter_category' => 'HESA disability',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => '1735',
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => rand(0..submitted_to_date),
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => rand(0..submitted_previous_cycle),
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            'nonprovider_filter' => 54,
            'nonprovider_filter_category' => 'HESA disability',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => '1735',
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => rand(0..submitted_to_date),
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => rand(0..submitted_previous_cycle),
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            'nonprovider_filter' => 98,
            'nonprovider_filter_category' => 'HESA disability',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => '1735',
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => rand(0..submitted_to_date),
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => rand(0..submitted_previous_cycle),
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            'nonprovider_filter' => 55,
            'nonprovider_filter_category' => 'HESA disability',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => '1735',
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => rand(0..submitted_to_date),
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => rand(0..submitted_previous_cycle),
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            'nonprovider_filter' => 51,
            'nonprovider_filter_category' => 'HESA disability',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => '1735',
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => rand(0..submitted_to_date),
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => rand(0..submitted_previous_cycle),
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            'nonprovider_filter' => 95,
            'nonprovider_filter_category' => 'HESA disability',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => '1735',
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => rand(0..submitted_to_date),
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => rand(0..submitted_previous_cycle),
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
        ]
      end
    end

    trait :ethnic_group do
      category { :ethnic_group }
      statistics do
        [
          {
            'nonprovider_filter' => 'White',
            'nonprovider_filter_category' => 'Ethnic group',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => '1735',
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => rand(0..submitted_to_date),
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => rand(0..submitted_previous_cycle),
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            'nonprovider_filter' => 'Prefer not to say',
            'nonprovider_filter_category' => 'Ethnic group',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => '1735',
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => rand(0..submitted_to_date),
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => rand(0..submitted_previous_cycle),
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            'nonprovider_filter' => 'Mixed Or Multiple Ethnic Groups',
            'nonprovider_filter_category' => 'Ethnic group',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => '1735',
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => rand(0..submitted_to_date),
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => rand(0..submitted_previous_cycle),
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            'nonprovider_filter' => 'Black, African, Black British Or Caribbean',
            'nonprovider_filter_category' => 'Ethnic group',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => '1735',
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => rand(0..submitted_to_date),
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => rand(0..submitted_previous_cycle),
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            'nonprovider_filter' => 'Another Ethnic Group',
            'nonprovider_filter_category' => 'Ethnic group',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => '1735',
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => rand(0..submitted_to_date),
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => rand(0..submitted_previous_cycle),
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            'nonprovider_filter' => 'Asian Or Asian British',
            'nonprovider_filter_category' => 'Ethnic group',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => '1735',
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => rand(0..submitted_to_date),
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => rand(0..submitted_previous_cycle),
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
        ]
      end
    end

    trait :age_group do
      category { :age_group }
      statistics do
        [
          {
            'nonprovider_filter' => 'Unknown',
            'nonprovider_filter_category' => 'Age group',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => '1735',
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => rand(0..submitted_to_date),
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => rand(0..submitted_previous_cycle),
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            'nonprovider_filter' => '65 and over',
            'nonprovider_filter_category' => 'Age group',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => '1735',
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => rand(0..submitted_to_date),
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => rand(0..submitted_previous_cycle),
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            'nonprovider_filter' => '60 to 64',
            'nonprovider_filter_category' => 'Age group',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => '1735',
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => rand(0..submitted_to_date),
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => rand(0..submitted_previous_cycle),
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            'nonprovider_filter' => '55 to 59',
            'nonprovider_filter_category' => 'Age group',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => '1735',
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => rand(0..submitted_to_date),
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => rand(0..submitted_previous_cycle),
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            'nonprovider_filter' => '40 to 44',
            'nonprovider_filter_category' => 'Age group',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => '1735',
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => rand(0..submitted_to_date),
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => rand(0..submitted_previous_cycle),
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            'nonprovider_filter' => '45 to 49',
            'nonprovider_filter_category' => 'Age group',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => '1735',
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => rand(0..submitted_to_date),
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => rand(0..submitted_previous_cycle),
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            'nonprovider_filter' => '50 to 54',
            'nonprovider_filter_category' => 'Age group',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => '1735',
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => rand(0..submitted_to_date),
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => rand(0..submitted_previous_cycle),
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            'nonprovider_filter' => '35 to 39',
            'nonprovider_filter_category' => 'Age group',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => '1735',
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => rand(0..submitted_to_date),
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => rand(0..submitted_previous_cycle),
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            'nonprovider_filter' => '30 to 34',
            'nonprovider_filter_category' => 'Age group',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => '1735',
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => rand(0..submitted_to_date),
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => rand(0..submitted_previous_cycle),
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            'nonprovider_filter' => '18 to 24',
            'nonprovider_filter_category' => 'Age group',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => '1735',
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => rand(0..submitted_to_date),
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => rand(0..submitted_previous_cycle),
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            'nonprovider_filter' => '25 to 29',
            'nonprovider_filter_category' => 'Age group',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => '1735',
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => rand(0..submitted_to_date),
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => rand(0..submitted_previous_cycle),
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
        ]
      end
    end
  end
end
