FactoryBot.define do
  factory :regional_edi_report, class: '::Publications::RegionalEdiReport' do
    recruitment_cycle_year { 2026 }
    cycle_week { 16 }
    generation_date { Time.zone.local(recruitment_cycle_year, 6, 1) }
    publication_date { Time.zone.local(recruitment_cycle_year, 6, 1) }
    region { :all_of_england }
    category { :sex }

    transient do
      submitted_to_date { rand(100..100_00) }
      submitted_previous_cycle { rand(0..submitted_to_date) }

      offered_to_date { rand(0..submitted_to_date) }
      offered_previous_cycle { rand(0..submitted_previous_cycle) }

      accepted_to_date { rand(0..(submitted_to_date / 2)) }
      recruited_rate { accepted_to_date.to_f / submitted_to_date }

      accepted_last_cycle { rand(0..(submitted_previous_cycle / 2)) }
      recruited_rate_last_cycle { accepted_last_cycle.to_f / submitted_previous_cycle }
    end

    statistics do
      filter_report_type = region == :all_of_england ? 'nonprovider_filter' : 'nonregion_filter'
      filter_category_type = region == :all_of_england ? 'nonprovider_filter_category' : 'nonregion_filter_category'
      [
        {
          filter_report_type => 'Unknown',
          filter_category_type => 'Sex',
          'cycle_week' => cycle_week,
          'recruitment_cycle_year' => recruitment_cycle_year,
          'provider_id' => nil,
          'number_of_candidates_submitted_to_date' => submitted_to_date,
          'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
          'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
          'number_of_candidates_with_offers_to_date' => rand(0..submitted_to_date),
          'number_of_candidates_with_offers_to_same_date_previous_cycle' => rand(0..submitted_previous_cycle),
          'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
          'offer_rate_to_date' => 0.0,
          'offer_rate_to_same_date_previous_cycle' => 0.25,
          'number_of_candidates_accepted_to_date' => accepted_to_date,
          'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
          'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
          'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
          'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
          'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
          'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
          'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
          'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
          'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
          'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
          'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
          'recruited_rate_to_date' => recruited_rate,
          'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
        },
        {
          filter_report_type => 'Other',
          filter_category_type => 'Sex',
          'cycle_week' => cycle_week,
          'recruitment_cycle_year' => recruitment_cycle_year,
          'provider_id' => nil,
          'number_of_candidates_submitted_to_date' => submitted_to_date,
          'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
          'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
          'number_of_candidates_with_offers_to_date' => offered_to_date,
          'number_of_candidates_with_offers_to_same_date_previous_cycle' => offered_previous_cycle,
          'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
          'offer_rate_to_date' => 0.0,
          'offer_rate_to_same_date_previous_cycle' => 0.25,
          'number_of_candidates_accepted_to_date' => accepted_to_date,
          'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
          'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0.8333333333333334,
          'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
          'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
          'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
          'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 3,
          'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 6,
          'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
          'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 8,
          'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.2424242424242424,
          'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.275,
          'recruited_rate_to_date' => recruited_rate,
          'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
        },
        {
          filter_report_type => 'Prefer not to say',
          filter_category_type => 'Sex',
          'cycle_week' => cycle_week,
          'recruitment_cycle_year' => recruitment_cycle_year,
          'provider_id' => nil,
          'number_of_candidates_submitted_to_date' => submitted_to_date,
          'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
          'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
          'number_of_candidates_with_offers_to_date' => offered_to_date,
          'number_of_candidates_with_offers_to_same_date_previous_cycle' => offered_previous_cycle,
          'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
          'offer_rate_to_date' => 0.0,
          'offer_rate_to_same_date_previous_cycle' => 0.25,
          'number_of_candidates_accepted_to_date' => accepted_to_date,
          'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
          'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0.9375,
          'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 3,
          'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 3,
          'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => 1.0,
          'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 33,
          'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 31,
          'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 1.064516129032258,
          'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 49,
          'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.2258064516129032,
          'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.2307692307692308,
          'recruited_rate_to_date' => recruited_rate,
          'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
        },
        {
          filter_report_type => 'Female',
          filter_category_type => 'Sex',
          'cycle_week' => cycle_week,
          'recruitment_cycle_year' => recruitment_cycle_year,
          'provider_id' => nil,
          'number_of_candidates_submitted_to_date' => submitted_to_date,
          'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
          'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
          'number_of_candidates_with_offers_to_date' => offered_to_date,
          'number_of_candidates_with_offers_to_same_date_previous_cycle' => offered_previous_cycle,
          'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
          'offer_rate_to_date' => 0.0,
          'offer_rate_to_same_date_previous_cycle' => 0.25,
          'number_of_candidates_accepted_to_date' => accepted_to_date,
          'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
          'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0.9801940715140237,
          'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 404,
          'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 348,
          'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => 1.160919540229885,
          'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 2818,
          'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 1880,
          'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 1.498936170212766,
          'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 4877,
          'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.2659504853310066,
          'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.2109808371154816,
          'recruited_rate_to_date' => recruited_rate,
          'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
        },
        {
          filter_report_type => 'Male',
          filter_category_type => 'Sex',
          'cycle_week' => cycle_week,
          'recruitment_cycle_year' => recruitment_cycle_year,
          'provider_id' => nil,
          'number_of_candidates_submitted_to_date' => submitted_to_date,
          'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
          'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
          'number_of_candidates_with_offers_to_date' => offered_to_date,
          'number_of_candidates_with_offers_to_same_date_previous_cycle' => offered_previous_cycle,
          'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
          'offer_rate_to_date' => 0.0,
          'offer_rate_to_same_date_previous_cycle' => 0.25,
          'number_of_candidates_accepted_to_date' => accepted_to_date,
          'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
          'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 1.04973075704783,
          'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 264,
          'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 207,
          'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => 1.27536231884058,
          'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 2792,
          'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 1751,
          'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 1.594517418617933,
          'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 5198,
          'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.3788905896931263,
          'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.3181253879577902,
          'recruited_rate_to_date' => recruited_rate,
          'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
        },
      ]
    end

    trait :disability do
      category { :disability }
      statistics do
        filter_report_type = region == :all_of_england ? 'nonprovider_filter' : 'nonregion_filter'
        filter_category_type = region == :all_of_england ? 'nonprovider_filter_category' : 'nonregion_filter_category'
        [
          {
            filter_report_type => 58,
            filter_category_type => 'HESA disability',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => nil,
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => offered_to_date,
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => offered_previous_cycle,
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            filter_report_type => 57,
            filter_category_type => 'HESA disability',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => nil,
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => offered_to_date,
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => offered_previous_cycle,
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            filter_report_type => 59,
            filter_category_type => 'HESA disability',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => nil,
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => offered_to_date,
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => offered_previous_cycle,
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            filter_report_type => 98,
            filter_category_type => 'HESA disability',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => nil,
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => offered_to_date,
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => offered_previous_cycle,
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            filter_report_type => 55,
            filter_category_type => 'HESA disability',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => nil,
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => offered_to_date,
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => offered_previous_cycle,
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            filter_report_type => 51,
            filter_category_type => 'HESA disability',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => nil,
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => offered_to_date,
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => offered_previous_cycle,
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            filter_report_type => 95,
            filter_category_type => 'HESA disability',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => nil,
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => offered_to_date,
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => offered_previous_cycle,
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            filter_report_type => 53,
            filter_category_type => 'HESA disability',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => nil,
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => offered_to_date,
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => offered_previous_cycle,
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            filter_report_type => 96,
            filter_category_type => 'HESA disability',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => nil,
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => offered_to_date,
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => offered_previous_cycle,
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            filter_report_type => 56,
            filter_category_type => 'HESA disability',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => nil,
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => offered_to_date,
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => offered_previous_cycle,
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            filter_report_type => 54,
            filter_category_type => 'HESA disability',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => nil,
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => offered_to_date,
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => offered_previous_cycle,
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
        ]
      end
    end

    trait :ethnic_group do
      category { :ethnic_group }
      statistics do
        filter_report_type = region == :all_of_england ? 'nonprovider_filter' : 'nonregion_filter'
        filter_category_type = region == :all_of_england ? 'nonprovider_filter_category' : 'nonregion_filter_category'
        [
          {
            filter_report_type => 'White',
            filter_category_type => 'Ethnic group',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => nil,
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => offered_to_date,
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => offered_previous_cycle,
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            filter_report_type => 'Mixed Or Multiple Ethnic Groups',
            filter_category_type => 'Ethnic group',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => nil,
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => offered_to_date,
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => offered_previous_cycle,
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            filter_report_type => 'Prefer not to say',
            filter_category_type => 'Ethnic group',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => nil,
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => offered_to_date,
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => offered_previous_cycle,
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            filter_report_type => 'Black, African, Black British Or Caribbean',
            filter_category_type => 'Ethnic group',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => nil,
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => offered_to_date,
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => offered_previous_cycle,
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            filter_report_type => 'Asian Or Asian British',
            filter_category_type => 'Ethnic group',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => nil,
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => offered_to_date,
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => offered_previous_cycle,
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            filter_report_type => 'Another Ethnic Group',
            filter_category_type => 'Ethnic group',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => nil,
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => offered_to_date,
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => offered_previous_cycle,
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
        ]
      end
    end

    trait :age_group do
      category { :age_group }
      statistics do
        filter_report_type = region == :all_of_england ? 'nonprovider_filter' : 'nonregion_filter'
        filter_category_type = region == :all_of_england ? 'nonprovider_filter_category' : 'nonregion_filter_category'
        [
          {
            filter_report_type => 'Unknown',
            filter_category_type => 'Age group',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => nil,
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => offered_to_date,
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => offered_previous_cycle,
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            filter_report_type => '65 and over',
            filter_category_type => 'Age group',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => nil,
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => offered_to_date,
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => offered_previous_cycle,
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            filter_report_type => '60 to 64',
            filter_category_type => 'Age group',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => nil,
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => offered_to_date,
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => offered_previous_cycle,
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            filter_report_type => '55 to 59',
            filter_category_type => 'Age group',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => nil,
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => offered_to_date,
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => offered_previous_cycle,
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            filter_report_type => '50 to 54',
            filter_category_type => 'Age group',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => nil,
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => offered_to_date,
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => offered_previous_cycle,
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            filter_report_type => '18 to 24',
            filter_category_type => 'Age group',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => nil,
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => offered_to_date,
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => offered_previous_cycle,
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            filter_report_type => '45 to 49',
            filter_category_type => 'Age group',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => nil,
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => offered_to_date,
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => offered_previous_cycle,
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            filter_report_type => '40 to 44',
            filter_category_type => 'Age group',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => nil,
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => offered_to_date,
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => offered_previous_cycle,
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            filter_report_type => '35 to 39',
            filter_category_type => 'Age group',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => nil,
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => offered_to_date,
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => offered_previous_cycle,
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            filter_report_type => '30 to 34',
            filter_category_type => 'Age group',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => nil,
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => offered_to_date,
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => offered_previous_cycle,
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
          {
            filter_report_type => '25 to 29',
            filter_category_type => 'Age group',
            'cycle_week' => cycle_week,
            'recruitment_cycle_year' => recruitment_cycle_year,
            'provider_id' => nil,
            'number_of_candidates_submitted_to_date' => submitted_to_date,
            'number_of_candidates_submitted_to_same_date_previous_cycle' => submitted_previous_cycle,
            'number_of_candidates_submitted_to_date_as_proportion_of_last_cycle' => 1.0,
            'number_of_candidates_with_offers_to_date' => offered_to_date,
            'number_of_candidates_with_offers_to_same_date_previous_cycle' => offered_previous_cycle,
            'number_of_candidates_with_offers_to_date_as_proportion_of_last_cycle' => 0.0,
            'offer_rate_to_date' => 0.0,
            'offer_rate_to_same_date_previous_cycle' => 0.25,
            'number_of_candidates_accepted_to_date' => accepted_to_date,
            'number_of_candidates_accepted_to_same_date_previous_cycle' => accepted_last_cycle,
            'number_of_candidates_accepted_to_date_as_proportion_of_last_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_same_date_previous_cycle' => 0,
            'number_of_candidates_with_reconfirmed_offers_deferred_from_previous_cycle_to_date_as_proportion_of_last_cycle' => nil,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date' => 1,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_same_date_previous_cycle' => 2,
            'number_of_candidates_who_had_all_applications_rejected_this_cycle_to_date_as_proportion_of_last_cycle' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date' => 2,
            'number_of_candidates_who_had_an_inactive_application_this_cycle_to_date_as_proportion_of_submitted_candidates' => 0.5,
            'number_of_candidates_who_had_an_inactive_application_last_cycle_to_date_as_proportion_of_submitted_candidates_last_cycle' => 0.25,
            'recruited_rate_to_date' => recruited_rate,
            'recruited_rate_to_same_date_previous_cycle' => recruited_rate_last_cycle,
          },
        ]
      end
    end
  end
end
