version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      ruby-minor-and-patch:
        applies-to: version-updates
        update-types:
          - "patch"
          - "minor"
    ignore:
      - dependency-name: audited
      - dependency-name: faker
      - dependency-name: sidekiq
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      js-minor-and-patch:
        applies-to: version-updates
        update-types:
          - "patch"
          - "minor"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - DevOps
      - dependencies
      - github_actions
