---
EnableDefaultLinters: true
exclude:
  - '**/node_modules/**/*'
  - 'app/views/candidate_interface/account_recovery/new.html.erb'
  - 'app/views/candidate_interface/application_choices/index.html.erb'
  - 'app/views/candidate_interface/shared/_details.html.erb'
linters:
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/ArgumentAlignment:
        Enabled: false
      Layout/CommentIndentation:
        Enabled: false
      Layout/FirstArgumentIndentation:
        Enabled: false
      Layout/FirstArrayElementIndentation:
        Enabled: false
      Layout/FirstHashElementIndentation:
        Enabled: false
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
