require:
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot
  - ./lib/rubocop/cop/rspec/no_should_in_specs.rb
  - ./lib/rubocop/cop/application_api_controller.rb
  - ./lib/rubocop/cop/govuk/govuk_button_to.rb
  - ./lib/rubocop/cop/govuk/govuk_link_to.rb
  - ./lib/rubocop/cop/govuk/govuk_submit.rb

inherit_from:
  - .rubocop_todo.yml
  - ./config/rubocop/config/factory_bot.yml
  - ./config/rubocop/config/layout.yml
  - ./config/rubocop/config/lint.yml
  - ./config/rubocop/config/metrics.yml
  - ./config/rubocop/config/naming.yml
  - ./config/rubocop/config/rails.yml
  - ./config/rubocop/config/rake.yml
  - ./config/rubocop/config/rspec.yml
  - ./config/rubocop/config/style.yml

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'config/application.rb'
    - 'config/puma.rb'
    - 'config/environments/*'
    - 'config/initializers/nationalities.rb'
    - 'features/support/env.rb'
    - 'vendor/**/*'
    - 'jmeter/**/*'

Bundler/OrderedGems:
  Enabled: false

Style/OptionalBooleanParameter:
  Exclude:
    - 'app/workers/**/*'

# These files call RequestLocals.fetch. Unlike Hash#fetch it requires the
# fallback to be passed in a block
Style/RedundantFetchBlock:
  Exclude:
    - 'app/controllers/concerns/emit_request_events.rb'
    - 'app/models/concerns/entity_events.rb'

RSpec/NoShouldInSpecs:
  Enabled: true
  Exclude:
  - 'spec/smoke/candidate_login_spec.rb'
  - 'spec/system/candidate_interface/adviser_sign_up/candidate_becomes_eligible_for_adviser_spec.rb'
  - 'spec/system/candidate_interface/adviser_sign_up/candidate_signs_up_for_an_adviser_spec.rb'
  - 'spec/system/candidate_interface/carry_over/candidate_carries_over_different_application_states_spec.rb'
  - 'spec/system/candidate_interface/carry_over/candidate_carries_over_unsubmitted_application_spec.rb'
  - 'spec/system/candidate_interface/continuous_applications/adviser_sign_up/candidate_signs_up_for_an_adviser_spec.rb'
  - 'spec/system/candidate_interface/continuous_applications/carry_over/candidate_carries_over_spec.rb'
  - 'spec/system/candidate_interface/continuous_applications/course_selection/candidate_arrives_from_find_and_says_no_to_course_choice_spec.rb'
  - 'spec/system/candidate_interface/continuous_applications/course_selection/candidate_arrives_from_find_not_signed_in_spec.rb'
  - 'spec/system/candidate_interface/continuous_applications/course_selection/candidate_arrives_from_find_with_a_course_only_open_on_apply_spec.rb'
  - 'spec/system/candidate_interface/continuous_applications/course_selection/candidate_arrives_from_find_with_a_course_with_multiple_sites_spec.rb'
  - 'spec/system/candidate_interface/continuous_applications/course_selection/candidate_arrives_from_find_with_a_course_with_multiple_study_modes_spec.rb'
  - 'spec/system/candidate_interface/continuous_applications/course_selection/candidate_arrives_from_find_with_an_accepted_offer_spec.rb'
  - 'spec/system/candidate_interface/continuous_applications/course_selection/candidate_deletes_application_spec.rb'
  - 'spec/system/candidate_interface/continuous_applications/course_selection/candidate_edits_course_choices_spec.rb'
  - 'spec/system/candidate_interface/continuous_applications/course_selection/candidate_reaching_reapplication_limit_spec.rb'
  - 'spec/system/candidate_interface/continuous_applications/course_selection/candidate_reapplying_to_a_course_spec.rb'
  - 'spec/system/candidate_interface/continuous_applications/course_selection/candidate_selecting_a_course_spec.rb'
  - 'spec/system/candidate_interface/continuous_applications/course_selection/candidate_selecting_a_course_that_is_full_spec.rb'
  - 'spec/system/candidate_interface/continuous_applications/course_selection/candidate_selecting_a_course_with_multiple_sites_spec.rb'
  - 'spec/system/candidate_interface/continuous_applications/course_selection/candidate_selecting_a_duplicate_course_spec.rb'
  - 'spec/system/candidate_interface/continuous_applications/course_selection/candidate_selecting_a_duplicate_course_when_editing_spec.rb'
  - 'spec/system/candidate_interface/continuous_applications/entering_details/candidate_can_edit_some_sections_after_first_submission_spec.rb'
  - 'spec/system/candidate_interface/continuous_applications/entering_details/candidate_can_not_edit_some_personal_details_after_first_submission_spec.rb'
  - 'spec/system/candidate_interface/continuous_applications/entering_details/candidate_can_not_edit_some_sections_after_first_submission_spec.rb'
  - 'spec/system/candidate_interface/continuous_applications/entering_details/candidate_marking_section_complete_or_incomplete_spec.rb'
  - 'spec/system/candidate_interface/continuous_applications/submitting/candidate_can_not_submit_with_incomplete_details_spec.rb'
  - 'spec/system/candidate_interface/continuous_applications/submitting/candidate_is_redirected_away_from_complete_page_spec.rb'
  - 'spec/system/candidate_interface/continuous_applications/submitting/candidate_submitting_application_spec.rb'
  - 'spec/system/candidate_interface/continuous_applications/submitting/candidate_tries_to_submit_an_application_for_a_course_with_closed_application_spec.rb'
  - 'spec/system/candidate_interface/continuous_applications/submitting/candidate_tries_to_submit_an_application_for_course_unavailable_spec.rb'
  - 'spec/system/candidate_interface/continuous_applications/submitting/candidate_with_no_right_to_work_tries_to_submit_course_spec.rb'
  - 'spec/system/candidate_interface/continuous_applications/submitting/redirect_to_your_applications_spec.rb'
  - 'spec/system/candidate_interface/continuous_applications/viewing-application-choices/candidate_sees_all_their_applications_spec.rb'
  - 'spec/system/candidate_interface/continuous_applications/viewing-application-choices/candidate_views_personal_statement_js_disabled_spec.rb'
  - 'spec/system/candidate_interface/continuous_applications/viewing-application-choices/candidate_views_personal_statement_spec.rb'
  - 'spec/system/candidate_interface/entering_details/candidate_becoming_a_teacher_spec.rb'
  - 'spec/system/candidate_interface/entering_details/candidate_deletes_and_adds_other_qualifications_after_completing_the_section_spec.rb'
  - 'spec/system/candidate_interface/entering_details/candidate_edits_or_deletes_volunteering_section_after_competing_the_section_spec.rb'
  - 'spec/system/candidate_interface/entering_details/candidate_edits_or_deletes_volunteering_section_with_restructured_work_history_active_spec.rb'
  - 'spec/system/candidate_interface/entering_details/candidate_entering_contact_details_spec.rb'
  - 'spec/system/candidate_interface/entering_details/candidate_entering_disability_info_spec.rb'
  - 'spec/system/candidate_interface/entering_details/candidate_entering_interview_preferences_spec.rb'
  - 'spec/system/candidate_interface/entering_details/candidate_entering_other_qualification_btec_spec.rb'
  - 'spec/system/candidate_interface/entering_details/candidate_entering_other_qualification_spec.rb'
  - 'spec/system/candidate_interface/entering_details/candidate_entering_personal_details_spec.rb'
  - 'spec/system/candidate_interface/entering_details/candidate_entering_volunteering_experience_spec.rb'
  - 'spec/system/candidate_interface/entering_details/candidate_personal_statement_spec.rb'
  - 'spec/system/candidate_interface/entering_details/change_gcse_spec.rb'
  - 'spec/system/candidate_interface/entering_details/degrees/candidate_adding_unknown_degrees_spec.rb'
  - 'spec/system/candidate_interface/entering_details/degrees/candidate_delete_and_replace_degrees_spec.rb'
  - 'spec/system/candidate_interface/entering_details/degrees/candidate_editing_international_degrees_spec.rb'
  - 'spec/system/candidate_interface/entering_details/degrees/candidate_entering_degrees_spec.rb'
  - 'spec/system/candidate_interface/entering_details/degrees/candidate_entering_international_degrees_spec.rb'
  - 'spec/system/candidate_interface/entering_details/international_candidate_enters_their_other_qualification_spec.rb'
  - 'spec/system/candidate_interface/entering_details/restructured_work_history/candidate_deleting_work_history_spec.rb'
  - 'spec/system/candidate_interface/entering_details/restructured_work_history/candidate_entering_restructured_work_history_add_job_spec.rb'
  - 'spec/system/candidate_interface/entering_details/restructured_work_history/candidate_entering_work_history_breaks_spec.rb'
  - 'spec/system/candidate_interface/entering_details/restructured_work_history/candidate_entering_work_history_full_time_education_spec.rb'
  - 'spec/system/candidate_interface/entering_details/restructured_work_history/candidate_entering_work_history_not_worked_spec.rb'
  - 'spec/system/candidate_interface/feedback/candidate_completes_the_feedback_form_spec.rb'
  - 'spec/system/candidate_interface/feedback/candidate_submits_application_with_feedback_form_previously_completed_spec.rb'
  - 'spec/system/candidate_interface/navigation_tabs_spec.rb'
  - 'spec/system/candidate_interface/offers_and_withdrawals/candidate_accepts_offer_and_is_redirected_when_tries_to_access_some_pages_spec.rb'
  - 'spec/system/candidate_interface/offers_and_withdrawals/candidate_accepts_offer_continuous_applications_spec.rb'
  - 'spec/system/candidate_interface/offers_and_withdrawals/candidate_accepts_offer_from_previous_cycle_spec.rb'
  - 'spec/system/candidate_interface/offers_and_withdrawals/candidate_accepts_offer_spec.rb'
  - 'spec/system/candidate_interface/offers_and_withdrawals/candidate_defers_offer_and_is_redirected_when_tries_to_access_some_pages_spec.rb'
  - 'spec/system/candidate_interface/post_offer/offer_deferred_spec.rb'
  - 'spec/system/candidate_interface/post_offer/pending_conditions_spec.rb'
  - 'spec/system/candidate_interface/post_offer/recruited_spec.rb'
  - 'spec/system/candidate_interface/references/candidate_add_references_spec.rb'
  - 'spec/system/candidate_interface/references/candidate_request_references_continuous_applications_spec.rb'
  - 'spec/system/candidate_interface/references/candidate_request_references_spec.rb'
  - 'spec/system/candidate_interface/references/candidate_views_their_references_on_the_post_offer_dashboard_continuous_applications_spec.rb'
  - 'spec/system/candidate_interface/references/candidate_views_their_references_on_the_post_offer_dashboard_from_previous_cycle_spec.rb'
  - 'spec/system/candidate_interface/references/candidate_views_their_references_on_the_post_offer_dashboard_spec.rb'
  - 'spec/system/candidate_interface/signup_and_signin/candidate_account_spec.rb'
  - 'spec/system/candidate_interface/signup_and_signin/candidate_signs_up_using_magic_link_with_an_invalid_token_spec.rb'
  - 'spec/system/candidate_interface/signup_and_signin/two_candidates_sign_in_on_same_machine_spec.rb'
  - 'spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_personal_details_section_spec.rb'
  - 'spec/system/candidate_interface/submitting/candidate_submits_a_duplicate_application_spec.rb'
  - 'spec/system/candidate_interface/submitting/international_candidate_submitting_application_spec.rb'
  - 'spec/system/inactive_application_spec.rb'
  - 'spec/system/monthly_statistics/monthly_statistics_page_spec.rb'
  - 'spec/system/provider_interface/authentication_spec.rb'
  - 'spec/system/provider_interface/change_existing_offer_ske_standard_flow_spec.rb'
  - 'spec/system/provider_interface/first_login_spec.rb'
  - 'spec/system/provider_interface/make_offer_ske_language_flow_spec.rb'
  - 'spec/system/provider_interface/make_offer_ske_standard_flow_spec.rb'
  - 'spec/system/provider_interface/provider_application_filter_by_subject_spec.rb'
  - 'spec/system/provider_interface/provider_applications_filter_spec.rb'
  - 'spec/system/provider_interface/provider_applications_pagination_spec.rb'
  - 'spec/system/provider_interface/provider_applications_search_spec.rb'
  - 'spec/system/provider_interface/provider_can_recruit_with_pending_ske_condition_spec.rb'
  - 'spec/system/provider_interface/provider_changes_conditions_on_an_offer_spec.rb'
  - 'spec/system/provider_interface/provider_edits_condition_statuses_spec.rb'
  - 'spec/system/provider_interface/provider_manages_application_interviews_spec.rb'
  - 'spec/system/provider_interface/provider_marks_conditions_as_met_spec.rb'
  - 'spec/system/provider_interface/provider_marks_conditions_as_not_met_spec.rb'
  - 'spec/system/provider_interface/provider_removes_conditions_from_an_offer_spec.rb'
  - 'spec/system/provider_interface/provider_reports_page_spec.rb'
  - 'spec/system/provider_interface/provider_sees_empty_state_spec.rb'
  - 'spec/system/provider_interface/provider_signs_in_from_new_device_spec.rb'
  - 'spec/system/provider_interface/provider_user_exports_applications_to_csv_spec.rb'
  - 'spec/system/provider_interface/provider_uses_webchat_spec.rb'
  - 'spec/system/provider_interface/provider_views_the_references_tab_on_manage_spec.rb'
  - 'spec/system/provider_interface/sandbox_emails_spec.rb'
  - 'spec/system/provider_interface/see_activity_log_spec.rb'
  - 'spec/system/provider_interface/see_applications_for_accrediting_provider_spec.rb'
  - 'spec/system/provider_interface/see_applications_spec.rb'
  - 'spec/system/provider_interface/see_individual_application_as_pdf_spec.rb'
  - 'spec/system/provider_interface/see_individual_application_personal_statement_spec.rb'
  - 'spec/system/provider_interface/see_updated_applications_post_submission_spec.rb'
  - 'spec/system/publications/v2/monthly_statistics/visit_monthly_statistics_spec.rb'
  - 'spec/system/referee_interface/referee_can_submit_a_reference_from_an_application_in_any_state_spec.rb'
  - 'spec/system/referee_interface/referee_refuses_to_give_a_reference_from_previous_cycle_spec.rb'
  - 'spec/system/referee_interface/referee_refuses_to_give_a_reference_spec.rb'
  - 'spec/system/register_api/register_receives_application_spec.rb'
  - 'spec/system/support_interface/add_audit_comment_spec.rb'
  - 'spec/system/support_interface/adding_a_new_provider_user_spec.rb'
  - 'spec/system/support_interface/adding_provider_to_existing_provider_user_spec.rb'
  - 'spec/system/support_interface/api_tokens/create_token_spec.rb'
  - 'spec/system/support_interface/api_tokens/revoke_token_spec.rb'
  - 'spec/system/support_interface/audit_trail_spec.rb'
  - 'spec/system/support_interface/authentication_spec.rb'
  - 'spec/system/support_interface/blazer_sql_spec.rb'
  - 'spec/system/support_interface/bulk_upload_a_single_provider_user_spec.rb'
  - 'spec/system/support_interface/bulk_upload_multiple_provider_users_spec.rb'
  - 'spec/system/support_interface/change_course_choice_for_a_deferred_application_spec.rb'
  - 'spec/system/support_interface/change_english_gcse_spec.rb'
  - 'spec/system/support_interface/change_maths_gcse_spec.rb'
  - 'spec/system/support_interface/change_offer_conditions_spec.rb'
  - 'spec/system/support_interface/change_offer_language_ske_conditions_spec.rb'
  - 'spec/system/support_interface/change_offer_ske_conditions_spec.rb'
  - 'spec/system/support_interface/change_offered_course_for_a_submitted_application_spec.rb'
  - 'spec/system/support_interface/change_science_gcse_spec.rb'
  - 'spec/system/support_interface/delete_reference_spec.rb'
  - 'spec/system/support_interface/duplicate_matches_spec.rb'
  - 'spec/system/support_interface/edit_candidate_account_status_spec.rb'
  - 'spec/system/support_interface/editing_address_details_spec.rb'
  - 'spec/system/support_interface/editing_applicant_details_spec.rb'
  - 'spec/system/support_interface/editing_degree_spec.rb'
  - 'spec/system/support_interface/editing_other_qualification_spec.rb'
  - 'spec/system/support_interface/editing_permissions_for_a_provider_user_spec.rb'
  - 'spec/system/support_interface/editing_personal_statment_spec.rb'
  - 'spec/system/support_interface/editing_reference_spec.rb'
  - 'spec/system/support_interface/feature_flags_spec.rb'
  - 'spec/system/support_interface/immigration_status_spec.rb'
  - 'spec/system/support_interface/managing_provider_permissions_spec.rb'
  - 'spec/system/support_interface/managing_support_users_spec.rb'
  - 'spec/system/support_interface/provider_onboarding_spec.rb'
  - 'spec/system/support_interface/providers_and_courses_spec.rb'
  - 'spec/system/support_interface/reasons_for_rejection_dashboard_spec.rb'
  - 'spec/system/support_interface/remove_and_restore_a_support_user_spec.rb'
  - 'spec/system/support_interface/removed_support_user_spec.rb'
  - 'spec/system/support_interface/removing_a_provider_user_spec.rb'
  - 'spec/system/support_interface/see_applications_spec.rb'
  - 'spec/system/support_interface/see_candidates_spec.rb'
  - 'spec/system/support_interface/see_individual_application_spec.rb'
  - 'spec/system/support_interface/see_monthly_statistics_reports_spec.rb'
  - 'spec/system/support_interface/service_performance_spec.rb'
  - 'spec/system/support_interface/sidekiq_admin_spec.rb'
  - 'spec/system/support_interface/unauthorized_spec.rb'
  - 'spec/system/support_interface/validation_errors_candidate_spec.rb'
  - 'spec/system/support_interface/validation_errors_candidate_summary_spec.rb'
  - 'spec/system/support_interface/validation_errors_provider_spec.rb'
  - 'spec/system/support_interface/validation_errors_provider_summary_spec.rb'
  - 'spec/system/support_interface/validation_errors_vendor_api_spec.rb'
  - 'spec/system/support_interface/validation_errors_vendor_api_summary_spec.rb'
  - 'spec/system/support_interface/vendor_api_monitoring_spec.rb'
  - 'spec/system/support_interface/viewing_provider_permissions_spec.rb'
  - 'spec/system/temporarily_editable_sections_spec.rb'
  - 'spec/system/vendor_api/vendor_receives_application_spec.rb'
  - 'spec/system/wizard_cache_cleared_spec.rb'


Govuk:
  Include:
    - 'app/views/**/*'
    - 'app/components/**/*'

Govuk/GovukLinkTo:
  Exclude:
    # link_to in components that use their own link classes
    - 'app/components/utility/header_component.html.erb'
    - 'app/components/support_interface/tile_component.html.erb'
    # link_to in filter component
    - 'app/components/utility/filter_component.html.erb'
    # link_to in manual error summaries
    - 'app/views/candidate_interface/references/review/show.html.erb'
    - 'app/views/candidate_interface/unsubmitted_application_form/review.html.erb'
    # link_to in footers
    - 'app/views/layouts/_footer.html'
    - 'app/views/layouts/_footer_meta_candidate.html.erb'
    - 'app/views/layouts/_footer_meta_provider.html.erb'
    # link_to for kaminari pagination links
    - 'app/views/kaminari/_next_page.html.erb'
    - 'app/views/kaminari/_prev_page.html.erb'

# TODO: These cops are broken (as of rubocop-rails 2.21.1) and need to be disabled
# until they are fixed by future versions of rubocop-rails
Rails/RedundantActiveRecordAllMethod:
  Enabled: false

Rails/FindEach:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Exclude:
    - 'db/migrate/20191022145559_install_audited.rb'
    - 'db/migrate/20191212113810_create_provider_users.rb'

Rails/DangerousColumnNames:
  Exclude:
    - 'db/migrate/20191022131332_create_id_on_application_choices.rb'
    - 'db/migrate/20200124114452_add_primary_key_to_provider_users_providers.rb'
