require 'rails_helper'

RSpec.describe SupportInterface::MinisterialReportExport do
  describe '#call' do
    it 'generates the full report with the correct totals' do
      test_subject = described_class.new

      allow(test_subject).to receive(:subject_status_count).and_return(
        { %w[03 awaiting_provider_decision] => 3,
          %w[Q3 awaiting_provider_decision] => 1,
          %w[11 rejected] => 1,
          %w[02 offer_deferred] => 1,
          %w[Q3 rejected] => 2,
          %w[V1 rejected] => 1,
          %w[W1 awaiting_provider_decision] => 2,
          %w[Q3 offer] => 1,
          %w[Q3 unsubmitted] => 1,
          %w[V1 offer_withdrawn] => 1,
          %w[07 unsubmitted] => 1,
          %w[Q3 interviewing] => 1,
          %w[C6 offer] => 1,
          %w[W3 conditions_not_met] => 1,
          %w[V1 cancelled] => 1,
          %w[06 rejected] => 1,
          %w[F1 recruited] => 1,
          %w[02 rejected] => 1,
          %w[06 offer] => 1,
          %w[11 offer_deferred] => 1,
          %w[C1 offer] => 2,
          %w[02 interviewing] => 1,
          %w[DT offer_withdrawn] => 1,
          %w[07 awaiting_provider_decision] => 2,
          %w[Q3 declined] => 1,
          %w[00 withdrawn] => 2,
          %w[01 recruited] => 1,
          %w[08 rejected] => 1,
          %w[06 declined] => 1,
          %w[24 awaiting_provider_decision] => 1,
          %w[02 pending_conditions] => 1,
          %w[01 declined] => 1,
          %w[V6 interviewing] => 1,
          %w[06 awaiting_provider_decision] => 1,
          %w[Q3 offer_deferred] => 2,
          %w[F1 unsubmitted] => 1,
          %w[07 recruited] => 1,
          %w[01 awaiting_provider_decision] => 2,
          %w[V6 offer] => 1,
          %w[07 pending_conditions] => 1,
          %w[13 conditions_not_met] => 1,
          %w[V6 rejected] => 1,
          %w[00 awaiting_provider_decision] => 1,
          %w[07 offer] => 1,
          %w[07 rejected] => 1 },
      )

      data = test_subject.call

      expect(data).to contain_exactly(
        {
          subject: :art_and_design,
          applications: 2,
          offer_received: 0,
          accepted: 0,
          application_declined: 0,
          application_rejected: 0,
        },
        {
          subject: :biology,
          applications: 2,
          offer_received: 2,
          accepted: 0,
          application_declined: 0,
          application_rejected: 0,
        },
        {
          subject: :business_studies,
          applications: 1,
          offer_received: 0,
          accepted: 0,
          application_declined: 0,
          application_rejected: 1,
        },
        {
          subject: :chemistry,
          applications: 2,
          offer_received: 1,
          accepted: 1,
          application_declined: 0,
          application_rejected: 0,
        },
        {
          subject: :classics,
          applications: 0,
          offer_received: 0,
          accepted: 0,
          application_declined: 0,
          application_rejected: 0,
        },
        {
          subject: :computing,
          applications: 2,
          offer_received: 1,
          accepted: 1,
          application_declined: 0,
          application_rejected: 1,
        },
        {
          subject: :design_and_technology,
          applications: 1,
          offer_received: 0,
          accepted: 0,
          application_declined: 0,
          application_rejected: 1,
        },
        {
          subject: :drama,
          applications: 1,
          offer_received: 1,
          accepted: 0,
          application_declined: 0,
          application_rejected: 0,
        },
        {
          subject: :english,
          applications: 9,
          offer_received: 3,
          accepted: 2,
          application_declined: 1,
          application_rejected: 2,
        },
        {
          subject: :geography,
          applications: 0,
          offer_received: 0,
          accepted: 0,
          application_declined: 0,
          application_rejected: 0,
        },
        {
          subject: :history,
          applications: 3,
          offer_received: 0,
          accepted: 0,
          application_declined: 1,
          application_rejected: 2,
        },
        {
          subject: :mathematics,
          applications: 0,
          offer_received: 0,
          accepted: 0,
          application_declined: 0,
          application_rejected: 0,
        },
        {
          subject: :modern_foreign_languages,
          applications: 1,
          offer_received: 0,
          accepted: 0,
          application_declined: 0,
          application_rejected: 0,
        },
        {
          subject: :music,
          applications: 1,
          offer_received: 1,
          accepted: 0,
          application_declined: 0,
          application_rejected: 0,
        },
        {
          subject: :other,
          applications: 0,
          offer_received: 0,
          accepted: 0,
          application_declined: 0,
          application_rejected: 0,
        },
        {
          subject: :physical_education,
          applications: 1,
          offer_received: 1,
          accepted: 0,
          application_declined: 0,
          application_rejected: 0,
        },
        {
          subject: :physics,
          applications: 0,
          offer_received: 0,
          accepted: 0,
          application_declined: 0,
          application_rejected: 0,
        },
        {
          subject: :religious_education,
          applications: 3,
          offer_received: 1,
          accepted: 0,
          application_declined: 0,
          application_rejected: 1,
        },
        {
          subject: :stem,
          applications: 6,
          offer_received: 4,
          accepted: 2,
          application_declined: 0,
          application_rejected: 1,
        },
        {
          subject: :ebacc,
          applications: 19,
          offer_received: 7,
          accepted: 4,
          application_declined: 2,
          application_rejected: 5,
        },
        {
          subject: :primary,
          applications: 11,
          offer_received: 4,
          accepted: 3,
          application_declined: 3,
          application_rejected: 1,
        },
        {
          subject: :secondary,
          applications: 29,
          offer_received: 11,
          accepted: 4,
          application_declined: 2,
          application_rejected: 8,
        },
        {
          subject: :total,
          applications: 40,
          offer_received: 15,
          accepted: 7,
          application_declined: 5,
          application_rejected: 9,
        },
      )
    end
  end
end
