require 'rails_helper'

RSpec.describe SupportInterface::StructuredReasonsForRejectionExport do
  describe '#data_for_export' do
    it 'returns an array of hashes containing structured reasons for rejection data' do
      application_choice_one = create(
        :application_choice,
        :with_structured_rejection_reasons,
        structured_rejection_reasons: {
          course_full_y_n: 'Yes',
          safeguarding_y_n: 'Yes',
          qualifications_y_n: 'Yes',
          safeguarding_concerns: %w[candidate_disclosed_information vetting_disclosed_information other],
          candidate_behaviour_y_n: 'Yes',
          candidate_behaviour_other: 'behaviour',
          quality_of_application_y_n: 'Yes',
          other_advice_or_feedback_y_n: nil,
          performance_at_interview_y_n: 'Yes',
          qualifications_other_details: 'details',
          offered_on_another_course_y_n: 'Yes',
          honesty_and_professionalism_y_n: 'Yes',
          other_advice_or_feedback_details: nil,
          offered_on_another_course_details: 'offered',
          candidate_behaviour_what_to_improve: 'behaviour',
          qualifications_which_qualifications: %w[no_maths_gcse no_english_gcse no_science_gcse no_degree other],
          safeguarding_concerns_other_details: 'd',
          honesty_and_professionalism_concerns: %w[information_false_or_inaccurate plagiarism references other],
          quality_of_application_other_details: 'details',
          interested_in_future_applications_y_n: nil,
          why_are_you_rejecting_this_application: nil,
          performance_at_interview_what_to_improve: 'improve',
          quality_of_application_other_what_to_improve: 'improve',
          candidate_behaviour_what_did_the_candidate_do: %w[didnt_reply_to_interview_offer didnt_attend_interview other],
          honesty_and_professionalism_concerns_other_details: 'details',
          quality_of_application_which_parts_needed_improvement: %w[personal_statement subject_knowledge other],
          honesty_and_professionalism_concerns_plagiarism_details: 'no',
          honesty_and_professionalism_concerns_references_details: 'yes',
          quality_of_application_subject_knowledge_what_to_improve: 'subject',
          quality_of_application_personal_statement_what_to_improve: 'statement',
          safeguarding_concerns_vetting_disclosed_information_details: 'd',
          safeguarding_concerns_candidate_disclosed_information_details: 'd',
          honesty_and_professionalism_concerns_information_false_or_inaccurate_details: 'yes',
        },
      )

      application_choice_two = create(
        :application_choice,
        :with_structured_rejection_reasons,
        structured_rejection_reasons: {
          qualifications_y_n: 'Yes',
          qualifications_other_details: 'Not good',
          qualifications_which_qualifications: %w[no_maths_gcse other],
        },
      )

      expect(described_class.new.data_for_export).to eq(
        [{
          'Candidate ID' => application_choice_one.application_form_id,
          'Application ID' => application_choice_one.id,
          'Something you did' => true,
          'Didn’t reply to our interview offer' => true,
          'Didn’t attend interview' => true,
          'Something you did other reason - details' => application_choice_one.structured_rejection_reasons['candidate_behaviour_other'],
          'Candidate behaviour - what to improve' => application_choice_one.structured_rejection_reasons['candidate_behaviour_what_to_improve'],
          'Quality of application' => true,
          'Personal statement' => true,
          'Personal statement - what to improve' => application_choice_one.structured_rejection_reasons['quality_of_application_personal_statement_what_to_improve'],
          'Subject knowledge' => true,
          'Subject knowledge - what to improve' => application_choice_one.structured_rejection_reasons['quality_of_application_subject_knowledge_what_to_improve'],
          'Quality of application - what to improve' => application_choice_one.structured_rejection_reasons['quality_of_application_other_what_to_improve'],
          'Quality of application other reason - details' => application_choice_one.structured_rejection_reasons['quality_of_application_other_details'],
          'Qualifications' => true,
          'No Maths GCSE grade 4 (C) or above, or valid equivalent' => true,
          'No English GCSE grade 4 (C) or above, or valid equivalent' => true,
          'No Science GCSE grade 4 (C) or above, or valid equivalent (for primary applicants)' => true,
          'No degree' => true,
          'Qualifications other reason - details' => application_choice_one.structured_rejection_reasons['qualifications_other_details'],
          'Performance at interview' => true,
          'Performance at interview - what to improve' => application_choice_one.structured_rejection_reasons['performance_at_interview_what_to_improve'],
          'Course full' => true,
          'They offered you a place on another course' => true,
          'Honesty and professionalism' => true,
          'Information given on application form false or inaccurate' => true,
          'Information given on application form false or inaccurate - details' => application_choice_one.structured_rejection_reasons['honesty_and_professionalism_concerns_information_false_or_inaccurate_details'],
          'Evidence of plagiarism in personal statement or elsewhere' => true,
          'Evidence of plagiarism in personal statement or elsewhere - details' => application_choice_one.structured_rejection_reasons['honesty_and_professionalism_concerns_plagiarism_details'],
          'References didn’t support application' => true,
          'References didn’t support application - details' => application_choice_one.structured_rejection_reasons['honesty_and_professionalism_concerns_references_details'],
          'Honesty and professionalism other reason - details' => application_choice_one.structured_rejection_reasons['honesty_and_professionalism_concerns_other_details'],
          'Safeguarding issues' => true,
          'Information disclosed by candidate makes them unsuitable to work with children' => true,
          'Information disclosed by candidate makes them unsuitable to work with children - details' => application_choice_one.structured_rejection_reasons['safeguarding_concerns_candidate_disclosed_information_details'],
          'Information revealed by our vetting process makes the candidate unsuitable to work with children' => true,
          'Information revealed by our vetting process makes the candidate unsuitable to work with children - details' => application_choice_one.structured_rejection_reasons['safeguarding_concerns_vetting_disclosed_information_details'],
          'Safeguarding issues other reason - details' => application_choice_one.structured_rejection_reasons['safeguarding_concerns_other_details'],
          'Additional advice' => false,
          'Future applications' => false,
          'why are you rejecting this application details' => nil,
        },
         {
           'Candidate ID' => application_choice_two.application_form_id,
           'Application ID' => application_choice_two.id,
           'Something you did' => false,
           'Didn’t reply to our interview offer' => false,
           'Didn’t attend interview' => false,
           'Something you did other reason - details' => nil,
           'Candidate behaviour - what to improve' => nil,
           'Quality of application' => false,
           'Personal statement' => false,
           'Personal statement - what to improve' => nil,
           'Subject knowledge' => false,
           'Subject knowledge - what to improve' => nil,
           'Quality of application - what to improve' => nil,
           'Quality of application other reason - details' => nil,
           'Qualifications' => true,
           'No Maths GCSE grade 4 (C) or above, or valid equivalent' => true,
           'No English GCSE grade 4 (C) or above, or valid equivalent' => false,
           'No Science GCSE grade 4 (C) or above, or valid equivalent (for primary applicants)' => false,
           'No degree' => false,
           'Qualifications other reason - details' => application_choice_two.structured_rejection_reasons['qualifications_other_details'],
           'Performance at interview' => false,
           'Performance at interview - what to improve' => nil,
           'Course full' => false,
           'They offered you a place on another course' => false,
           'Honesty and professionalism' => false,
           'Information given on application form false or inaccurate' => false,
           'Information given on application form false or inaccurate - details' => nil,
           'Evidence of plagiarism in personal statement or elsewhere' => false,
           'Evidence of plagiarism in personal statement or elsewhere - details' => nil,
           'References didn’t support application' => false,
           'References didn’t support application - details' => nil,
           'Honesty and professionalism other reason - details' => nil,
           'Safeguarding issues' => false,
           'Information disclosed by candidate makes them unsuitable to work with children' => false,
           'Information disclosed by candidate makes them unsuitable to work with children - details' => nil,
           'Information revealed by our vetting process makes the candidate unsuitable to work with children' => false,
           'Information revealed by our vetting process makes the candidate unsuitable to work with children - details' => nil,
           'Safeguarding issues other reason - details' => nil,
           'Additional advice' => false,
           'Future applications' => false,
           'why are you rejecting this application details' => nil,
         }],
      )
    end
  end
end
