require 'rails_helper'

RSpec.describe SupportInterface::StructuredReasonsForRejectionExport do
  describe '#data_for_export' do
    it 'returns an array of hashes containing structured reasons for rejection data' do
      application_choice = create(
        :application_choice,
        :with_structured_rejection_reasons,
        structured_rejection_reasons: {
          course_full_y_n: 'Yes',
          safeguarding_y_n: 'Yes',
          qualifications_y_n: 'Yes',
          safeguarding_concerns: %w[candidate_disclosed_information vetting_disclosed_information other],
          candidate_behaviour_y_n: 'Yes',
          candidate_behaviour_other: 'behaviour',
          quality_of_application_y_n: 'Yes',
          other_advice_or_feedback_y_n: nil,
          performance_at_interview_y_n: 'Yes',
          qualifications_other_details: 'details',
          offered_on_another_course_y_n: 'Yes',
          honesty_and_professionalism_y_n: 'Yes',
          other_advice_or_feedback_details: nil,
          offered_on_another_course_details: 'offered',
          candidate_behaviour_what_to_improve: 'behaviour',
          qualifications_which_qualifications: %w[no_maths_gcse no_english_gcse no_science_gcse no_degree other],
          safeguarding_concerns_other_details: 'd',
          honesty_and_professionalism_concerns: %w[information_false_or_inaccurate plagiarism references other],
          quality_of_application_other_details: 'details',
          interested_in_future_applications_y_n: nil,
          why_are_you_rejecting_this_application: nil,
          performance_at_interview_what_to_improve: 'improve',
          quality_of_application_other_what_to_improve: 'improve',
          candidate_behaviour_what_did_the_candidate_do: %w[didnt_reply_to_interview_offer didnt_attend_interview other],
          honesty_and_professionalism_concerns_other_details: 'details',
          quality_of_application_which_parts_needed_improvement: %w[personal_statement subject_knowledge other],
          honesty_and_professionalism_concerns_plagiarism_details: 'no',
          honesty_and_professionalism_concerns_references_details: 'yes',
          quality_of_application_subject_knowledge_what_to_improve: 'subject',
          quality_of_application_personal_statement_what_to_improve: 'statement',
          safeguarding_concerns_vetting_disclosed_information_details: 'd',
          safeguarding_concerns_candidate_disclosed_information_details: 'd',
          honesty_and_professionalism_concerns_information_false_or_inaccurate_details: 'yes',
        },
      )

      expect(described_class.new.data_for_export).to contain_exactly(
        {
          'Candidate ID' => application_choice.id,
          'Candidate behaviour' => true,
          'Candidate behaviour - Didn’t reply to our interview offer' => true,
          'Candidate behaviour - Didn’t attend an interview' => true,
          'Candidate behaviour - Other detail' => application_choice.structured_rejection_reasons['candidate_behaviour_other'],
          'Quality of application (y/n)' => true,
          'Quality of personal statement' => true,
          'Quality of personal statement details' => application_choice.structured_rejection_reasons['quality_of_application_personal_statement_what_to_improve'],
          'Quality of subject knowledge' => true,
          'Quality of subject knowledge details' => application_choice.structured_rejection_reasons['quality_of_application_subject_knowledge_what_to_improve'],
          'Quality of application other' => application_choice.structured_rejection_reasons['quality_of_application_other_details'],
          'Qualifications (y/n)' => true,
          'No Maths GCSE grade 4 (C) or above, or valid equivalent' => true,
          'No English GCSE grade 4 (C) or above, or valid equivalent' => true,
          'No Science GCSE grade 4 (C) or above, or valid equivalent (for primary applicants)' => true,
          'No degree' => true,
          'Qualifications other' => application_choice.structured_rejection_reasons['qualifications_other_details'],
          'Performance at interview' => true,
          'Performance at interview - What to improve' => application_choice.structured_rejection_reasons['performance_at_interview_what_to_improve'],
          'Course was full?' => true,
          'Offered another course' => true,
          'Concerns about honesty and professionalism' => true,
          'Honesty and professionalism - False or inaccurate information' => true,
          'Honesty and professionalism - Information given on application form false or inaccurate' => application_choice.structured_rejection_reasons['honesty_and_professionalism_concerns_information_false_or_inaccurate_details'],
          'Honesty and professionalism - Plagiarism' => true,
          'Honesty and professionalism - Evidence of plagiarism in personal statement or elsewhere' => application_choice.structured_rejection_reasons['honesty_and_professionalism_concerns_plagiarism_details'],
          'Honesty and professionalism - References' => true,
          'Honesty and professionalism - References didn’t support application' => application_choice.structured_rejection_reasons['honesty_and_professionalism_concerns_references_details'],
          'Honesty and professionalism - Other Concerns about honesty and professionalism' => application_choice.structured_rejection_reasons['honesty_and_professionalism_concerns_other_details'],
          'Safeguarding' => true,
          'Information disclosed by candidate makes them unsuitable to work with children' => true,
          'Information disclosed by candidate makes them unsuitable to work with children - detail' => application_choice.structured_rejection_reasons['safeguarding_concerns_candidate_disclosed_information_details'],
          'Information revealed by our vetting process makes the candidate unsuitable to work with children' => true,
          'Information revealed by our vetting process makes the candidate unsuitable to work with children - detail' => application_choice.structured_rejection_reasons['safeguarding_concerns_vetting_disclosed_information_details'],
          'Safeguarding other' => application_choice.structured_rejection_reasons['safeguarding_concerns_other_details'],
        },
      )
    end
  end
end
