common_columns:
  - total
  - applications_status

custom_columns:
  secondary_subject:
    type: string
    enum:
      - Art and design
      - Science
      - Biology
      - Business studies
      - Chemistry
      - Citizenship
      - Classics
      - Communication and media studies
      - Computing
      - Dance
      - Design and technology
      - Drama
      - Economics
      - English
      - Geography
      - Health and social care
      - History
      - Mathematics
      - Modern foreign languages
      - Music
      - Philosophy
      - Physical education
      - Physics
      - Psychology
      - Religious education
      - Social sciences
      - Further education
