common_columns:
  - total
  - applications_status

custom_columns:
  provider_area:
    type: string
    description: The region the provider is based in
    enum:
      - East
      - East Midlands
      - London
      - North East
      - North West
      - South East
      - South West
      - West Midlands
      - Yorkshire and The Humber
