common_columns:
- sex
- ethnicity
- disability
- total

custom_columns:
  custom_age_group:
    type: string
    description: The applicant age group
    example: Under 25

  degree_class:
    type: string
    description: The applicant degree grade
    example: Pass

  domicile:
    type: string
    description: The applicant domicile
    example: UK

  pending_conditions:
    type: integer
    description: The number of applications that have offers pending conditions for this subject

  recruited:
    type: integer
    description: The number of applications that have been recruited for this subject
