common_columns:
  age_group:
    type: string
    description: The applicant age group
    example: Under 25

  sex:
    type: string
    description: The applicant sex
    example: Female

  ethnicity:
    type: string
    description: The applicant ethnicity
    example: Mixed - White and Asian

  disability:
    type: string
    description: The applicant disability status
    example: Multiple disabilities

custom_columns:
  degree_class:
    type: string
    description: The applicant degree grade
    example: Pass

  domicile:
    type: string
    description: The applicant domicile
    example: UK

  adjusted_applications:
    type: integer
    description: The number of applications that have received offers for this subject

  adjusted_offers:
    type: integer
    description: The number of applications that have accepted offers for this subject

  pending_conditions:
    type: integer
    description: The number of applications that have declined offers for this subject

  recruited:
    type: integer
    description: The number of applications that have been rejected for this subject

  total:
    type: integer
    description: The total number of applications
