name: Copy database from PaaS to AKS
description: Backup PaaS postgres DB and restore to AKS

inputs:
  environment:
    description: Environment to backup and restore
    required: true
  azure-credentials-paas:
    required: true
  azure-credentials-aks:
    required: true
  slack-webhook:
    required: true

runs:
  using: composite
  steps:
    - name: Set KV environment variables
      shell: bash
      run: |
        tf_vars_file=terraform/paas/workspace_variables/${{ inputs.environment }}.tfvars.json
        echo "key_vault_name=$(jq -r '.key_vault_name' ${tf_vars_file})" >> $GITHUB_ENV
        echo "key_vault_infra_secret_name=$(jq -r '.key_vault_infra_secret_name' ${tf_vars_file})" >> $GITHUB_ENV
        echo "paas_space_name=$(jq -r '.paas_cf_space' ${tf_vars_file})" >> $GITHUB_ENV
        echo "paas_app_environment=$(jq -r '.paas_app_environment' ${tf_vars_file})" >> $GITHUB_ENV

    - uses: azure/login@v1
      with:
        creds: ${{ inputs.azure-credentials-paas }}

    - uses: DFE-Digital/keyvault-yaml-secret@v1
      id: get-secrets
      with:
        keyvault: ${{ env.key_vault_name }}
        secret: ${{ env.key_vault_infra_secret_name }}
        key: CF_USER,CF_PASSWORD

    - name: Setup cf cli
      uses: DFE-Digital/github-actions/setup-cf-cli@master
      with:
        CF_USERNAME:   ${{ steps.get-secrets.outputs.CF_USER }}
        CF_PASSWORD:   ${{ steps.get-secrets.outputs.CF_PASSWORD }}
        CF_SPACE_NAME: ${{ env.paas_space_name }}
        INSTALL_CONDUIT: true

    - name: Setup postgres client
      uses: DFE-Digital/github-actions/install-postgres-client@master

    - name: Set environment variable
      shell: bash
      run: echo "backup_file_name=apply_${{ inputs.environment }}.sql.gz" >> $GITHUB_ENV

    - name: Backup ${{ inputs.environment }} DB
      shell: bash
      run: |
        cf conduit apply-postgres-${{ env.paas_app_environment }} -- pg_dump -E utf8 --compress=1 --clean --if-exists --no-owner --verbose --no-password -f ${{ env.backup_file_name }}
        cf logout
        az logout

#
# Now restore to the equivalent AKS env database
#

    - name: Set KV environment variables for AKS
      shell: bash
      run: |
        tf_vars_file=terraform/aks/workspace_variables/${{ inputs.environment }}_aks.tfvars.json
        echo "key_vault_name=$(jq -r '.key_vault_name' ${tf_vars_file})" >> $GITHUB_ENV
        echo "key_vault_infra_secret_name=$(jq -r '.key_vault_infra_secret_name' ${tf_vars_file})" >> $GITHUB_ENV
        echo "cluster=$(jq -r '.cluster' ${tf_vars_file})" >> $GITHUB_ENV
        echo "aks_app_environment=$(jq -r '.paas_app_environment' ${tf_vars_file})" >> $GITHUB_ENV

    - uses: azure/login@v1
      with:
        creds: ${{ inputs.azure-credentials-aks }}

    - name: Set up environment variables
      shell: bash
      run: |
        case ${{ env.cluster }} in
          test)
            echo "cluster_rg=s189t01-tsc-ts-rg" >> $GITHUB_ENV
            echo "cluster_name=s189t01-tsc-test-aks" >> $GITHUB_ENV
            ;;
          production)
            echo "cluster_rg=s189p01-tsc-ps-rg" >> $GITHUB_ENV
            echo "cluster_name=s189p01-tsc-production-aks" >> $GITHUB_ENV
            ;;
          *)
            echo "unknown cluster"
            ;;
        esac
        echo "app_name=apply-${{ env.aks_app_environment }}" >> $GITHUB_ENV

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.26.1' # default is latest stable

    - name: K8 setup
      shell: bash
      run: |
        az aks get-credentials -g ${{ env.cluster_rg }} -n ${{ env.cluster_name }}
        make install-konduit

    - name: Restore backup to aks env database
      shell: bash
      run: |
        bin/konduit.sh -i ${{ env.backup_file_name }} -c ${{ env.app_name }} -- psql

    - name: Remove PaaS specific event triggers
      shell: bash
      run: |
        bin/konduit.sh ${{ env.app_name }} -- psql -c 'drop event trigger forbid_ddl_reader'
        bin/konduit.sh ${{ env.app_name }} -- psql -c 'drop event trigger make_readable'
        bin/konduit.sh ${{ env.app_name }} -- psql -c 'drop event trigger reassign_owned'
