{
 "title": "Michael",
 "description": "For Apply load tests",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "App",
    "query": "apply-prod, apply-sandbox, apply-staging, apply-qa, apply-load-test"
   },
   {
    "name": "db_service",
    "label": "Database service",
    "query": "apply-postgres-prod, apply-postgres-sandbox, apply-postgres-staging, apply-postgres-qa, apply-postgres-load-test"
   }
  ]
 },
 "panels": [
  {
   "title": "Rails reqs/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(rails_requests_total{app=\"$app\"}[5m]))"
    }
   ]
  },
  {
   "title": "Connections backlog",
   "type": "graph",
   "description": "Established but unaccepted connections in puma",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(puma_backlog{app=\"$app\"})"
    }
   ]
  },
  {
   "title": "JMeter actions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jmeter_total_count[1m])",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "JMeter response times (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jmeter_response_times_as_summary{quantile=\"0.99\"}",
     "legendFormat": "{{label}} {{code}}"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(cpu{app=\"$app\"})",
     "legendFormat": "max"
    },
    {
     "expr": "min(cpu{app=\"$app\"})",
     "legendFormat": "min"
    },
    {
     "expr": "avg(cpu{app=\"$app\"})",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "App crashes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(crash{app=\"$app\"}[1m]))",
     "legendFormat": "crash count"
    }
   ]
  },
  {
   "title": "Memory usage (Mb)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(memory_bytes{app=\"$app\"})/1048576",
     "legendFormat": "max"
    },
    {
     "expr": "min(memory_bytes{app=\"$app\"})/1048576",
     "legendFormat": "min"
    },
    {
     "expr": "avg(memory_bytes{app=\"$app\"})/1048576",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "Average response times (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1000 * avg by (controller, action, status) (increase(rails_request_duration_seconds_sum{app=\"$app\"}[5m]) / increase(rails_request_duration_seconds_count{app=\"$app\"}[5m]))",
     "legendFormat": "{{controller}}#{{action}} {{status}}"
    }
   ]
  },
  {
   "title": "Garbage collections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gc_count{app=\"$app\"}[5m]))"
    }
   ]
  },
  {
   "title": "% of time spent in database",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * (avg by (controller, action) (increase(rails_db_runtime_seconds_sum{app=\"$app\"}[5m]) / increase(rails_db_runtime_seconds_count{app=\"$app\"}[5m]))) / (avg by (controller, action) (increase(rails_request_duration_seconds_sum{app=\"$app\"}[5m]) / increase(rails_request_duration_seconds_count{app=\"$app\"}[5m])))",
     "legendFormat": "{{controller}}#{{action}}"
    }
   ]
  },
  {
   "title": "Allocated objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gc_total_allocated_objects{app=\"$app\"}[5m]))"
    }
   ]
  },
  {
   "title": "Response codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (jmeter_response_times_as_summary_count)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Outgoing HTTP requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_total{app=\"$app\"}[5m])) by (host)"
    }
   ]
  },
  {
   "title": "Database query durations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(rails_db_runtime_seconds_sum{app=\"$app\"}[5m]))"
    }
   ]
  },
  {
   "title": "Number of candidates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(apply_db_candidates{app=\"$app\"})"
    }
   ]
  },
  {
   "title": "Database CPU %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(cpu_percent{service=\"$db_service\"})",
     "legendFormat": "max"
    },
    {
     "expr": "min(cpu_percent{service=\"$db_service\"})",
     "legendFormat": "min"
    },
    {
     "expr": "avg(cpu_percent{service=\"$db_service\"})",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "Number of application choices",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(apply_db_application_choices{app=\"$app\"})"
    }
   ]
  },
  {
   "title": "Database IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(read_iops{service=\"$db_service\"})",
     "legendFormat": "read"
    },
    {
     "expr": "avg(write_iops{service=\"$db_service\"})",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Sidekiq jobs enqueued",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(sidekiq_jobs_enqueued_total{app=\"$app\"}[5m]))"
    }
   ]
  }
 ]
}