# rubocop:disable Style/StringLiterals
HESA_DEGREE_TYPES = [
  [1, "BEd"],
  [3, "BSc/Education"],
  [5, "BTech/Education"],
  [7, "BA/Education"],
  [9, "BA Combined Studies/Education of the Deaf"],
  [12, "BA with intercalated PGCE"],
  [51, "Bachelor of Arts(BA)"],
  [52, "Bachelor of Arts Economics(BA ECON)"],
  [53, "Bachelor of Arts in Architecture(BA ARCH)"],
  [54, "Bachelor of the Art of Obstetrics (BAO)"],
  [55, "Bachelor of Architecture(BA ARCH)"],
  [56, "Bachelor of Applied Science(B ASC)"],
  [57, "Bachelor of Agriculture(B AG)"],
  [58, "Bachelor of Accountancy(B ACC)"],
  [59, "Bachelor of Administration(B ADMIN)"],
  [60, "Bachelor of Business Administration(BBA)"],
  [61, "Bachelor of Combined Studies (BCS)"],
  [62, "Bachelor of Commerce(B COMM)"],
  [63, "Bachelor of Divinity(BD)"],
  [64, "Bachelor of Dental Surgery(BDS)"],
  [65, "Bachelor of Engineering(B ENG)"],
  [66, "Bachelor of Engineering with Business Studies(B ENG/BS)"],
  [67, "Bachelor of Fine Art(BFA)"],
  [68, "Bachelor of General Studies(BGS)"],
  [69, "Bachelor of Humanities (BH)"],
  [70, "Bachelor of Hygiene (B HYG)"],
  [71, "Bachelor of Law(LLB)"],
  [72, "Bachelor of Librarianship (B LIB)"],
  [73, "Bachelor of Librarianship and Info. Studies(BLS)"],
  [74, "Bachelor of Literature (B LITT)"],
  [75, "Bachelor of Land Economy(BL ECON)"],
  [76, "Bachelor of Medical Science(B MED SC)"],
  [77, "Bachelor of Medicine(BM)"],
  [78, "Bachelor of Metallurgy (B MET)"],
  [79, "Bachelor of Metallurgy and Engineering(B MET/EN)"],
  [80, "Bachelor of Music (B MU)"],
  [81, "Bachelor of Nursing (BN)"],
  [82, "Bachelor of Pharmacy(B PHARM)"],
  [83, "Bachelor of Science (B SC)"],
  [84, "Bachelor of Science Economics (BSC/ECO)"],
  [85, "Bachelor of Science &amp; Engineering (BSC/ENG)"],
  [86, "Bachelor of Science &amp; Technology (BSC/TEC)"],
  [87, "Bachelor of Science in Social Science (BSC SS)"],
  [88, "Bachelor of Science in Speech Therapy (BSC SPT)"],
  [89, "Bachelor of Social Science (BSS)"],
  [90, "Bachelor of Surgery (BS)"],
  [91, "Bachelor of Chirurgiae (B CH)"],
  [92, "Bachelor of Technology (B TECH)"],
  [93, "Bachelor of Theology (B THEOL)"],
  [94, "Bachelor of Veterinary Medicine (B VMED)"],
  [95, "Bachelor of Veterinary Medicine and Surgery (BVMS)"],
  [96, "Bachelor of Veterinary Science (B VSC)"],
  [97, "Bachelor of Education Scotland &amp; N Ireland (B ED)"],
  [98, "Bachelor of Philosophy (B PHIL)"],
  [200, "Master of Arts (MA)"],
  [201, "Master of Librarianship (M LIB)"],
  [202, "Master of Literature (M LITT)"],
  [203, "Master of Music (M MUS)"],
  [204, "Master of Philosophy (M PHIL)"],
  [205, "Master of Science (M SC)"],
  [206, "Master of Theology (M THEOL)"],
  [207, "Certificate of Membership of Cranfield Institute of Technology"],
  [208, "Master of Education (M ED)"],
  [209, "Master of Business Studies (M BS)"],
  [210, "Master of Social Studies (M SS)"],
  [211, "Master of Engineering (M ENG)"],
  [212, "Master of Law (M LAW)"],
  [213, "Master of Business Administration (MBA)"],
  [214, "Master of Chemistry (M CHEM)"],
  [215, "Master of Physics (M PHYS)"],
  [300, "Doctor of Divinity (DD)"],
  [301, "Doctor of Civil Law (DCL)"],
  [302, "Doctor of Medicine (MD)"],
  [303, "Doctor of Music (D MU)"],
  [304, "Doctor of Science (D SC)"],
  [305, "Doctor of Philosophy (D PHIL)"],
  [306, "PhD (PHD)"],
  [400, "First Degree"],
  [401, "Higher Degree"],
  [402, "Degree equivalent (inc. foreign qualifications)"],
  [999, "Unknown"],
].freeze
# rubocop:enable Style/StringLiterals
