HESA_DEGREE_TYPES = [
  [1, nil, 'BEd', :bachelor],
  [3, nil, 'BSc/Education', :bachelor],
  [5, nil, 'BTech/Education', :bachelor],
  [7, nil, 'BA/Education', :bachelor],
  [9, nil, 'BA Combined Studies/Education of the Deaf', :bachelor],
  [12, nil, 'BA with intercalated PGCE', :bachelor],
  [51, 'BA', 'Bachelor of Arts', :bachelor],
  [52, 'BA ECON', 'Bachelor of Arts Economics', :bachelor],
  [53, 'BA ARCH', 'Bachelor of Arts in Architecture', :bachelor],
  [54, 'BAO', 'Bachelor of the Art of Obstetrics', :bachelor],
  [55, 'BA ARCH', 'Bachelor of Architecture', :bachelor],
  [56, 'B ASC', 'Bachelor of Applied Science', :bachelor],
  [57, 'B AG', 'Bachelor of Agriculture', :bachelor],
  [58, 'B ACC', 'Bachelor of Accountancy', :bachelor],
  [59, 'B ADMIN', 'Bachelor of Administration', :bachelor],
  [60, 'BBA', 'Bachelor of Business Administration', :bachelor],
  [61, 'BCS', 'Bachelor of Combined Studies', :bachelor],
  [62, 'B COMM', 'Bachelor of Commerce', :bachelor],
  [63, 'BD', 'Bachelor of Divinity', :bachelor],
  [64, 'BDS', 'Bachelor of Dental Surgery', :bachelor],
  [65, 'B ENG', 'Bachelor of Engineering', :bachelor],
  [66, 'B ENG/BS', 'Bachelor of Engineering with Business Studies', :bachelor],
  [67, 'BFA', 'Bachelor of Fine Art', :bachelor],
  [68, 'BGS', 'Bachelor of General Studies', :bachelor],
  [69, 'BH', 'Bachelor of Humanities', :bachelor],
  [70, 'B HYG', 'Bachelor of Hygiene', :bachelor],
  [71, 'LLB', 'Bachelor of Law', :bachelor],
  [72, 'B LIB', 'Bachelor of Librarianship', :bachelor],
  [73, 'BLS', 'Bachelor of Librarianship and Info. Studies', :bachelor],
  [74, 'B LITT', 'Bachelor of Literature', :bachelor],
  [75, 'BL ECON', 'Bachelor of Land Economy', :bachelor],
  [76, 'B MED SC', 'Bachelor of Medical Science', :bachelor],
  [77, 'BM', 'Bachelor of Medicine', :bachelor],
  [78, 'B MET', 'Bachelor of Metallurgy', :bachelor],
  [79, 'B MET/EN', 'Bachelor of Metallurgy and Engineering', :bachelor],
  [80, 'B MU', 'Bachelor of Music', :bachelor],
  [81, 'BN', 'Bachelor of Nursing', :bachelor],
  [82, 'B PHARM', 'Bachelor of Pharmacy', :bachelor],
  [83, 'B SC', 'Bachelor of Science', :bachelor],
  [84, 'BSC/ECO', 'Bachelor of Science Economics', :bachelor],
  [85, 'BSC/ENG', 'Bachelor of Science &amp; Engineering', :bachelor],
  [86, 'BSC/TEC', 'Bachelor of Science &amp; Technology', :bachelor],
  [87, 'BSC SS', 'Bachelor of Science in Social Science', :bachelor],
  [88, 'BSC SPT', 'Bachelor of Science in Speech Therapy', :bachelor],
  [89, 'BSS', 'Bachelor of Social Science', :bachelor],
  [90, 'BS', 'Bachelor of Surgery', :bachelor],
  [91, 'B CH', 'Bachelor of Chirurgiae', :bachelor],
  [92, 'B TECH', 'Bachelor of Technology', :bachelor],
  [93, 'B THEOL', 'Bachelor of Theology', :bachelor],
  [94, 'B VMED', 'Bachelor of Veterinary Medicine', :bachelor],
  [95, 'BVMS', 'Bachelor of Veterinary Medicine and Surgery', :bachelor],
  [96, 'B VSC', 'Bachelor of Veterinary Science', :bachelor],
  [97, 'B ED', 'Bachelor of Education Scotland &amp; N Ireland', :bachelor],
  [98, 'B PHIL', 'Bachelor of Philosophy', :bachelor],

  [200, 'MA', 'Master of Arts', :master],
  [201, 'M LIB', 'Master of Librarianship', :master],
  [202, 'M LITT', 'Master of Literature', :master],
  [203, 'M MUS', 'Master of Music', :master],
  [204, 'M PHIL', 'Master of Philosophy', :master],
  [205, 'M SC', 'Master of Science', :master],
  [206, 'M THEOL', 'Master of Theology', :master],
  [207, nil, 'Certificate of Membership of Cranfield Institute of Technology', :master],
  [208, 'M ED', 'Master of Education', :master],
  [209, 'M BS', 'Master of Business Studies', :master],
  [210, 'M SS', 'Master of Social Studies', :master],
  [211, 'M ENG', 'Master of Engineering', :master],
  [212, 'M LAW', 'Master of Law', :master],
  [213, 'MBA', 'Master of Business Administration', :master],
  [214, 'M CHEM', 'Master of Chemistry', :master],
  [215, 'M PHYS', 'Master of Physics', :master],

  [300, 'DD', 'Doctor of Divinity', :doctor],
  [301, 'DCL', 'Doctor of Civil Law', :doctor],
  [302, 'MD', 'Doctor of Medicine', :doctor],
  [303, 'D MU', 'Doctor of Music', :doctor],
  [304, 'D SC', 'Doctor of Science', :doctor],
  [305, 'D PHIL', 'Doctor of Philosophy', :doctor],
  [306, nil, 'PhD', :doctor],

  [400, nil, 'First Degree', :other],
  [401, nil, 'Higher Degree', :other],
  [402, nil, 'Degree equivalent', :other],
  [999, nil, 'Unknown', :other],
].freeze
