HESA_DEGREE_GRADES = [
  [1, 'First class honours'],
  [2, 'Upper second-class honours (2:1)'],
  [3, 'Lower second-class honours (2:2)'],
  [4, 'Undivided second class honours'],
  [5, 'Third-class honours'],
  [6, 'Fourth class honours'],
  [7, 'Unclassified honours'],
  [8, 'Aegrotat'],
  [10, 'Ordinary degree'],
  [11, 'General degree'],
  [12, 'Distinction'],
  [13, 'Merit'],
  [14, 'Pass'],
  [98, 'Not applicable'],
  [99, 'Unknown'],
].freeze
