HESA_DEGREE_GRADES = [
  [1, 'First class honours', :main],
  [2, 'Upper second-class honours (2:1)', :main],
  [3, 'Lower second-class honours (2:2)', :main],
  [4, 'Undivided second class honours', :other],
  [5, 'Third-class honours', :main],
  [6, 'Fourth class honours', :other],
  [7, 'Unclassified', :other],
  [8, 'Aegrotat', :other],
  [10, 'Ordinary degree', :other],
  [11, 'General degree', :other],
  [12, 'Distinction', :main],
  [13, 'Merit', :main],
  [14, 'Pass', :main],
  [98, 'Not applicable', :main],
  [99, 'Unknown', :main],
].freeze
