# Taken from https://www.gov.uk/government/publications/nationalities
NATIONALITIES = [
  ['AL', 'Albanian'],
  ['AF', 'Afghan'],
  ['DZ', 'Algerian'],
  ['US', 'American'],
  ['AD', 'Andorran'],
  ['AO', 'Angolan'],
  ['AI', 'Anguillan'],
  ['AR', 'Argentine'],
  ['AM', 'Armenian'],
  ['AU', 'Australian'],
  ['AT', 'Austrian'],
  ['AZ', 'Azerbaijani'],
  ['BS', 'Bahamian'],
  ['BH', 'Bahraini'],
  ['BD', 'Bangladeshi'],
  ['BB', 'Barbadian'],
  ['BY', 'Belarusian'],
  ['BE', 'Belgian'],
  ['BZ', 'Belizean'],
  ['BJ', 'Beninese'],
  ['BM', 'Bermudian'],
  ['BT', 'Bhutanese'],
  ['BO', 'Bolivian'],
  ['BW', 'Botswanan'],
  ['BR', 'Brazilian'],
  ['GB', 'British'],
  ['VG', 'British Virgin Islander'],
  ['BN', 'Bruneian'],
  ['BG', 'Bulgarian'],
  ['BF', 'Burkinan'],
  ['MM', 'Burmese'],
  ['BI', 'Burundian'],
  ['KH', 'Cambodian'],
  ['CM', 'Cameroonian'],
  ['CA', 'Canadian'],
  ['CV', 'Cape Verdean'],
  ['KY', 'Cayman Islander'],
  ['CF', 'Central African'],
  ['TD', 'Chadian'],
  ['CL', 'Chilean'],
  ['CN', 'Chinese'],
  ['AG', 'Citizen of Antigua and Barbuda'],
  ['BA', 'Citizen of Bosnia and Herzegovina'],
  ['GW', 'Citizen of Guinea-Bissau'],
  ['KI', 'Citizen of Kiribati'],
  ['SC', 'Citizen of Seychelles'],
  ['DO', 'Citizen of the Dominican Republic'],
  ['VU', 'Citizen of Vanuatu'],
  ['CO', 'Colombian'],
  ['KM', 'Comoran'],
  ['CG', 'Congolese (Congo)'],
  ['CD', 'Congolese (DRC)'],
  ['CK', 'Cook Islander'],
  ['CR', 'Costa Rican'],
  ['HR', 'Croatian'],
  ['CU', 'Cuban'],
  ['CY', 'Cypriot'],
  ['GB', 'Cymraes'],
  ['GB', 'Cymro'],
  ['CZ', 'Czech'],
  ['DK', 'Danish'],
  ['DJ', 'Djiboutian'],
  ['DM', 'Dominican'],
  ['NL', 'Dutch'],
  ['TL', 'East Timorese'],
  ['EC', 'Ecuadorean'],
  ['EG', 'Egyptian'],
  ['AE', 'Emirati'],
  ['GQ', 'Equatorial Guinean'],
  ['ER', 'Eritrean'],
  ['EE', 'Estonian'],
  ['ET', 'Ethiopian'],
  ['FO', 'Faroese'],
  ['FJ', 'Fijian'],
  ['PH', 'Filipino'],
  ['FI', 'Finnish'],
  ['FR', 'French'],
  ['GA', 'Gabonese'],
  ['GM', 'Gambian'],
  ['GE', 'Georgian'],
  ['DE', 'German'],
  ['GH', 'Ghanaian'],
  ['GI', 'Gibraltarian'],
  ['GR', 'Greek'],
  ['GL', 'Greenlandic'],
  ['GD', 'Grenadian'],
  ['GU', 'Guamanian'],
  ['GT', 'Guatemalan'],
  ['GN', 'Guinean'],
  ['GY', 'Guyanese'],
  ['HT', 'Haitian'],
  ['HN', 'Honduran'],
  ['HK', 'Hong Konger'],
  ['HU', 'Hungarian'],
  ['IS', 'Icelandic'],
  ['IN', 'Indian'],
  ['ID', 'Indonesian'],
  ['IR', 'Iranian'],
  ['IQ', 'Iraqi'],
  ['IE', 'Irish'],
  ['IL', 'Israeli'],
  ['IT', 'Italian'],
  ['CI', 'Ivorian'],
  ['JM', 'Jamaican'],
  ['JP', 'Japanese'],
  ['JO', 'Jordanian'],
  ['KZ', 'Kazakh'],
  ['KE', 'Kenyan'],
  ['KN', 'Kittitian'],
  ['XK', 'Kosovan'],
  ['KW', 'Kuwaiti'],
  ['KG', 'Kyrgyz'],
  ['LA', 'Lao'],
  ['LV', 'Latvian'],
  ['LB', 'Lebanese'],
  ['LR', 'Liberian'],
  ['LY', 'Libyan'],
  ['LI', 'Liechtenstein citizen'],
  ['LT', 'Lithuanian'],
  ['LU', 'Luxembourger'],
  ['MO', 'Macanese'],
  ['MK', 'Macedonian'],
  ['MG', 'Malagasy'],
  ['MW', 'Malawian'],
  ['MY', 'Malaysian'],
  ['MV', 'Maldivian'],
  ['ML', 'Malian'],
  ['MT', 'Maltese'],
  ['MH', 'Marshallese'],
  ['MQ', 'Martiniquais'],
  ['MR', 'Mauritanian'],
  ['MU', 'Mauritian'],
  ['MX', 'Mexican'],
  ['FM', 'Micronesian'],
  ['MD', 'Moldovan'],
  ['MC', 'Monegasque'],
  ['MN', 'Mongolian'],
  ['ME', 'Montenegrin'],
  ['MS', 'Montserratian'],
  ['MA', 'Moroccan'],
  ['LS', 'Mosotho'],
  ['MZ', 'Mozambican'],
  ['NA', 'Namibian'],
  ['NR', 'Nauruan'],
  ['NP', 'Nepalese'],
  ['NZ', 'New Zealander'],
  ['NI', 'Nicaraguan'],
  ['NG', 'Nigerian'],
  ['NE', 'Nigerien'],
  ['NU', 'Niuean'],
  ['KP', 'North Korean'],
  ['GB', 'Northern Irish'],
  ['NO', 'Norwegian'],
  ['OM', 'Omani'],
  ['PK', 'Pakistani'],
  ['PW', 'Palauan'],
  ['PS', 'Palestinian'],
  ['PA', 'Panamanian'],
  ['PG', 'Papua New Guinean'],
  ['PY', 'Paraguayan'],
  ['PE', 'Peruvian'],
  ['PN', 'Pitcairn Islander'],
  ['PL', 'Polish'],
  ['PT', 'Portuguese'],
  ['GB', 'Prydeinig'],
  ['PR', 'Puerto Rican'],
  ['QA', 'Qatari'],
  ['RP', 'Romanian'],
  ['RU', 'Russian'],
  ['RW', 'Rwandan'],
  ['SV', 'Salvadorean'],
  ['SM', 'Sammarinese'],
  ['WS', 'Samoan'],
  ['ST', 'Sao Tomean'],
  ['SA', 'Saudi Arabian'],
  ['GB', 'Scottish'],
  ['SN', 'Senegalese'],
  ['RS', 'Serbian'],
  ['SL', 'Sierra Leonean'],
  ['SG', 'Singaporean'],
  ['SK', 'Slovak'],
  ['SI', 'Slovenian'],
  ['SB', 'Solomon Islander'],
  ['SO', 'Somali'],
  ['ZA', 'South African'],
  ['KR', 'South Korean'],
  ['SS', 'South Sudanese'],
  ['ES', 'Spanish'],
  ['LK', 'Sri Lankan'],
  ['SH', 'St Helenian'],
  ['LC', 'St Lucian'],
  ['SD', 'Sudanese'],
  ['SR', 'Surinamese'],
  ['SZ', 'Swazi'],
  ['SE', 'Swedish'],
  ['CH', 'Swiss'],
  ['SY', 'Syrian'],
  ['TW', 'Taiwanese'],
  ['TJ', 'Tajik'],
  ['TZ', 'Tanzanian'],
  ['TH', 'Thai'],
  ['TG', 'Togolese'],
  ['TO', 'Tongan'],
  ['TT', 'Trinidadian'],
  ['SH', 'Tristanian'],
  ['TN', 'Tunisian'],
  ['TR', 'Turkish'],
  ['TM', 'Turkmen'],
  ['TC', 'Turks and Caicos Islander'],
  ['TV', 'Tuvaluan'],
  ['UG', 'Ugandan'],
  ['UA', 'Ukrainian'],
  ['UY', 'Uruguayan'],
  ['UZ', 'Uzbek'],
  ['VA', 'Vatican citizen'],
  ['VE', 'Venezuelan'],
  ['VN', 'Vietnamese'],
  ['VC', 'Vincentian'],
  ['WF', 'Wallisian'],
  ['GB', 'Welsh'],
  ['YE', 'Yemeni'],
  ['ZM', 'Zambian'],
  ['ZW', 'Zimbabwean'],
].freeze

NATIONALITIES_BY_NAME = NATIONALITIES.map(&:reverse).to_h
NATIONALITY_DEMONYMS = NATIONALITIES.map(&:second)
