REGION_CODES = {
  'north east' => :north_east,
  'north west' => :north_west,
  'yorkshire and the humber' => :yorkshire_and_the_humber,
  'east midlands' => :east_midlands,
  'west midlands' => :west_midlands,
  'east of england' => :eastern,
  'london' => :london,
  'south east' => :south_east,
  'south west' => :south_west,
  'wales' => :wales,
  'scotland' => :scotland,
  'northern ireland' => :northern_ireland,
  'channel islands' => :channel_islands,
  'isle of man' => :isle_of_man,
}.freeze

UK_REGION_COUNTRY_MAPPING = {
  north_east: 'England',
  north_west: 'England',
  yorkshire_and_the_humber: 'England',
  east_midlands: 'England',
  west_midlands: 'England',
  eastern: 'England',
  london: 'England',
  south_east: 'England',
  south_west: 'England',
  wales: 'Wales',
  scotland: 'Scotland',
  northern_ireland: 'Northern Ireland',
}.freeze
