module Subjects
  PRIMARY_SUBJECT_NAMES = [
    'Primary',
    'Primary with English',
    'Primary with geography and history',
    'Primary with mathematics',
    'Primary with modern languages',
    'Primary with physical education',
    'Primary with science',
  ].freeze

  SECONDARY_SUBJECT_NAMES = [
    'Art and design',
    'Biology',
    'Business studies',
    'Chemistry',
    'Citizenship',
    'Classics',
    'Communication and media studies',
    'Computing',
    'Dance',
    'Design and technology',
    'Drama',
    'Economics',
    'English',
    'English as a second or other language',
    'Further education',
    'Geography',
    'Health and social care',
    'History',
    'Mathematics',
    'French',
    'German',
    'Mandarin',
    'Spanish',
    'Italian',
    'Japanese',
    'Modern Languages',
    'Modern languages (other)',
    'Russian',
    'Music',
    'Physical education',
    'Philosophy',
    'Physics',
    'Psychology',
    'Religious education',
    'Science',
    'Social sciences',
  ].freeze
end
