apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup-template
  namespace: development

spec:
  # Impossible date, so it never runs automatically
  schedule: "0 0 31 2 *"

  # Explicitly disable scheduling
  suspend: true

  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5

  jobTemplate:
    spec:
      backoffLimit: 0

      template:
        metadata:
          labels:
            app: postgres-backup
          annotations:
            logit.io/send: "true"
            fluentbit.io/exclude: "true"

        spec:
          restartPolicy: Never

          securityContext:
            seccompProfile:
              type: RuntimeDefault

          containers:
            - name: test-backup
              image: ghcr.io/dfe-digital/teacher-services-cloud-db-backup:2911-postgres-backup-via-aks

              envFrom:
                - configMapRef:
                    name: att-review-rdg-cbd61f8e6e40579925e74317515e8b73c4a55430

                - secretRef:
                    name: att-review-rdg-300a86bd2bb6d0c7a874679f84b290f57721f469
                    name: test-secret

              command:
                - /bin/bash
                - -c

              args:
                - |
                  set -euo pipefail

                  export BACKUP_NAME="postgres-$(date +%F-%H%M%S).dump"
                  echo $BACKUP_NAME

                  echo "running pg_dump"
                  pg_dump -d $DATABASE_URL -E utf8 --clean --compress=1 --if-exists --no-owner --verbose --no-password -f testdump.gz

                  echo "running azcopy"
                  azcopy cp ./testdump.gz "${AZURE_STORAGE_SAS_URL}"

                  #azcopy cp ./testdump.gz "${AZURE_STORAGE_SAS_URL}/${BACKUP_NAME}"
                  #azcopy cp ./testdump.gz "https://${AZURE_STORAGE_ACCOUNT_NAME}.blob.core.windows.net/${AZURE_STORAGE_CONTAINER}/${BACKUP_NAME}?${AZURE_STORAGE_ACCESS_KEY}"
                  #azcopy cp --from-to PipeBlob "https://${AZURE_STORAGE_ACCOUNT_NAME}.blob.core.windows.net/${AZURE_STORAGE_CONTAINER}/${BACKUP_NAME}?${AZURE_STORAGE_ACCESS_KEY}"


              resources:
                requests:
                  cpu: "500m"
                  memory: "1Gi"

                limits:
                  cpu: "1"
                  memory: "2Gi"

              securityContext:
                allowPrivilegeEscalation: false

                capabilities:
                  drop:
                    - ALL
                  add:
                    - NET_BIND_SERVICE
