trigger:
  batch: true
  # excluding these paths as this build will be trigged after gems-node-modules-image build is completed.
  paths:
    exclude:
      - Gemfile
      - Gemfile.lock
      - package.json
      - yarn.lock

pr:
  branches:
    include:
      - master
  # excluding these paths as this build will be trigged after gems-node-modules-image build is completed.
  paths:
    exclude:
      - Gemfile
      - Gemfile.lock
      - package.json
      - yarn.lock

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: Hello World
