candidate-withdrawal-reasons:
  applying-to-another-provider:
    accepted-another-offer: {}
    seen-a-course-that-suits-me-better: {}
    provider-has-not-replied-to-me: {}
    location-is-too-far-away: {}
    personal-circumstances-have-changed:
      concerns-about-cost-of-doing-course: {}
      concerns-about-having-enough-time-to-train: {}
      concerns-about-training-with-a-disability-or-health-condition: {}
      other: {}
    course-no-longer-available: {}
    other: {}
  change-or-update-application-with-this-provider:
    update-my-application-correct-an-error-or-add-information: {}
    change-study-pattern: {}
    apply-for-a-different-subject-with-the-same-provider: {}
    other: {}
  apply-in-the-future:
    personal-circumstances-have-changed:
      concerns-about-cost-of-doing-course: {}
      concerns-about-having-enough-time-to-train: {}
      concerns-about-training-with-a-disability-or-health-condition: {}
      other: {}
    gain-more-experience: {}
    improve-qualifications: {}
    other: {}
  do-not-want-to-train-anymore:
    personal-circumstances-have-changed:
      concerns-about-cost-of-doing-course: {}
      concerns-about-having-enough-time-to-train: {}
      concerns-about-training-with-a-disability-or-health-condition: {}
      other: {}
    another-career-path-or-accepted-a-job-offer: {}
    other: {}
  other: {}
