default: &default
  workers:
    - queues: [default]
      threads: <%= ENV.fetch("DEFAULT_QUEUE_THREADS", 1) %>
      processes: <%= ENV.fetch("DEFAULT_QUEUE_PROCESSES", 1) %>
      polling_interval: 1

    - queues: [low_priority]
      threads: <%= ENV.fetch("LOW_PRIORITY_QUEUE_THREADS", 1) %>
      processes: <%= ENV.fetch("LOW_PRIORITY_QUEUE_PROCESSES", 1) %>
      polling_interval: 2

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
