default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500

  workers:
    - queues: [default]
      threads: <%= ENV.fetch("DEFAULT_QUEUE_THREADS", 3) %>
      processes: <%= ENV.fetch("DEFAULT_QUEUE_PROCESSES", 2) %>
      polling_interval: 0.1

    - queues: [low_priority]
      threads: <%= ENV.fetch("LOW_PRIORITY_QUEUE_THREADS", 2) %>
      processes: <%= ENV.fetch("LOW_PRIORITY_QUEUE_PROCESSES", 2) %>
      polling_interval: 0.1

non_production: &non_production
  workers:
    - queues: [default]
      threads: <%= ENV.fetch("DEFAULT_QUEUE_THREADS", 3) %>
      processes: <%= ENV.fetch("DEFAULT_QUEUE_PROCESSES", 1) %>
      polling_interval: 0.1

    - queues: [low_priority]
      threads: <%= ENV.fetch("LOW_PRIORITY_QUEUE_THREADS", 2) %>
      processes: <%= ENV.fetch("LOW_PRIORITY_QUEUE_PROCESSES", 1) %>
      polling_interval: 0.1

review:
  <<: *non_production

staging:
  <<: *non_production

sandbox:
  <<: *non_production

development:
  <<: *non_production

test:
  <<: *non_production

production:
  <<: *default
