default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "*"
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1
    - queues: [ low_priority ]
      threads: 2
      polling_interval: 0.1
      processes: 3
  scheduler:
    dynamic_tasks_enabled: true
    polling_interval: 5

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
