- :id: applying_to_different_provider
  :label: I’m going to apply (or have applied) to a different training provider
- :id: applying_to_different_course_same_provider
  :label: I’m going to apply (or have applied) to a different course at the same training provider
- :id: concerns_about_cost
  :label: I have concerns about the cost of doing the course
- :id: course_not_available_anymore
  :label: The course is not available anymore
- :id: wait_to_start_course_too_long
  :label: The wait to start the course is too long
- :id: applying_to_teacher_training_next_year
  :label: I’ve decided to apply for teacher training next year
- :id: asked_to_withdraw
  :label: The training provider has asked me to withdraw
- :id: training_provider_has_not_responded
  :label: The training provider has not responded to me
- :id: training_location_too_far_away
  :label: The location I’m expected to train at is too far away
- :id: concerns_about_time_to_train
  :label: I have concerns that I will not have time to train
- :id: concerns_about_training_with_disability_or_health_condition
  :label: I have concerns about training with a disability or health condition
- :id: no_longer_want_to_train_to_teach
  :label: I do not want to train to be a teacher anymore
