require 'rails_helper'

RSpec.describe GenerateTestData do
  describe '#generate' do
    it 'generates test data' do
      expect { GenerateTestData.new(2).generate }
        .to change { Candidate.count }.by(2)
        .and change { ApplicationForm.count }.by(2)
        .and change { ApplicationChoice.count }.by_at_least(2)
    end

    it 'assigns all application choices to a single provider' do
      GenerateTestData.new(2).generate
      ApplicationChoice.all.each do |application_choice|
        expect(application_choice.provider.code).to eq 'ABC'
      end
    end

    it 'assigns all application choices to the specified provider' do
      GenerateTestData.new(2, create(:provider, code: 'DEF')).generate
      ApplicationChoice.all.each do |application_choice|
        expect(application_choice.provider.code).to eq 'DEF'
      end
    end

    it 'assigns all application choices to the application_complete state' do
      GenerateTestData.new(2).generate
      ApplicationChoice.all.each do |application_choice|
        expect(application_choice.status).to eq 'application_complete'
      end
    end

    it 'does not throw an error and creates an application when duplicate course codes are generated by faker' do
      provider = create(:provider, code: 'DEF')
      Faker::Config.random = Random.new(42)
      expect { GenerateTestData.new(1, provider).generate }.to change { ApplicationForm.count }.by(1)
      Faker::Config.random = Random.new(42)
      expect { GenerateTestData.new(1, provider).generate }.to change { ApplicationForm.count }.by(1)
    end

    it 'associates application forms to candidates with matching email addresses' do
      GenerateTestData.new(1, create(:provider, code: 'DEF')).generate
      application_form = ApplicationForm.first
      expect(application_form.candidate.email_address).to match application_form.first_name.downcase
      expect(application_form.candidate.email_address).to match application_form.last_name.downcase
    end
  end
end
