name: Backup database via AKS to Azure storage

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to backup
        required: true
        default: qa
        type: choice
        options:
        - qa
        - staging
        - sandbox
        - production

  schedule:
    - cron: "50 5 * * *" # 05:50 UTC

permissions:
  id-token: write

jobs:
  backup:
    name: Backup database via AKS
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment || 'production' }}
    env:
      DEPLOY_ENV: ${{ inputs.environment || 'production'  }}

    steps:
    - uses: actions/checkout@v6

    - name: Install kubectl
      uses: DFE-Digital/github-actions/set-kubectl@master

    - uses: azure/login@v3
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Set kubelogin environment
      uses: DFE-Digital/github-actions/set-kubelogin-environment@master
      with:
        azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
        azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}

    - name: Grant exec on scripts
      run: |
        chmod +x ./scripts/*.sh

    - name: Run backup AKS job
      run: make ci ${{ env.DEPLOY_ENV }} aks_db_job_backup

    - name: Notify teams channel on job failure
      if: ${{ failure() }}
      uses: DFE-Digital/github-actions/send-to-teams-channel@master
      with:
        teams-webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
        title: Postgres Backup Job (AKS)
        service:  ${{ vars.TEAMS_MSG_SERVICE_NAME }}
        message: |
          The Postgres backup of ${{ env.DEPLOY_ENV }} via AKS pod has failed

    - name: Notify teams channel on workflow success
      uses: DFE-Digital/github-actions/send-to-teams-channel@master
      with:
        teams-webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
        title: Postgres Backup Job (AKS)
        service:  ${{ vars.TEAMS_MSG_SERVICE_NAME }}
        status: good
        minimal: true
        message: |
          The Postgres backup of ${{ env.DEPLOY_ENV }} via AKS pod was successful
          