name: Disable maintenance

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options:
        - qa
        - production

jobs:
  disable-maintenance:
    name: Disable maintenance app
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}_aks

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set ARM and kubelogin environment
      uses: DFE-Digital/github-actions/set-kubelogin-environment@master
      with:
        azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Disable maintenance app
      run: make ci ${{ inputs.environment }}_aks disable-maintenance
