name: Restore Snapshot Database 
#Restores Snapshot Database apply-postgres-snapshot instance from nightly backup

on:
  workflow_dispatch:
    inputs:
      date-to-restore-from:
        description: The date of the backup to use in the restore in yyyy-MM-dd format
        required: true
      environment:
        description: GitHub environment to run the restore in
        type: choice
        default: qa
        options:
          - qa
          - prod

jobs:
  backup:
    name: Restore Snapshot Database (production)
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
      - name: Setup cf cli
        uses: DFE-Digital/github-actions/setup-cf-cli@master
        with:
          CF_USERNAME:   ${{ secrets.CF_USERNAME }}
          CF_PASSWORD:   ${{ secrets.CF_PASSWORD }}
          CF_SPACE_NAME: ${{ secrets.CF_SPACE }}
          INSTALL_CONDUIT: true

      - name: Setup postgres client
        uses: DFE-Digital/github-actions/install-postgres-client@master
        
      - name: Validate date-to-restore-from input
        run: if [[ ${{ github.event.inputs.date-to-restore-from }} =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; then echo "BACKUP_DATE=${BASH_REMATCH[0]}" >> $GITHUB_ENV; else exit 1; fi

      - name: Get backup file name
        run: | 
          az storage blob list --container ${{ github.event.inputs.environment }}-db-backup \
          --connection-string '${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}' \
          --query "[? contains(name, 'apply_${{ github.event.inputs.environment }}_${BACKUP_DATE}') && ends_with(name,'tar.gz')].name" | echo "BACKUP_ARCHIVE_NAME=$(jq -r .[0])" >> $GITHUB_ENV

      - name: Download backup
        run: |
          az storage blob download --container-name prod-db-backup --name ${BACKUP_ARCHIVE_NAME} --file ${BACKUP_ARCHIVE_NAME} \
          --connection-string '${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}'

      - name: Extract backup
        run: |
          BACKUP_FILE_NAME=$(tar -xvzf ${BACKUP_ARCHIVE_NAME})
          echo "BACKUP_FILE_NAME=${BACKUP_FILE_NAME}" >> $GITHUB_ENV

      - name: Restore backup to snapshot database
        run: cf conduit apply-postgres-snapshot -- psql < ${BACKUP_FILE_NAME}
